feat: sign up backend integration #P23-316
intive/patronage2023-js pull request #101
Opened 2023-05-18 15:01 UTC by wyola

## Sing-up - backend integration
task: https://tracker.intive.com/jira/browse/PATRO23-316

Nothing amazing to write about is happening here 😅

Right now backend does not accept `#` as special character in password. They will change it https://intive-apu8934.slack.com/archives/C051NK1TM29/p1684419851960659

2023-05-18 15:43 UTC, zuzannapaw reviewed
I only saw one thing, I don't know if this is our fault with choosing user's avatar, or maybe it's on the backend side, but when I want to sign up, I choose avatar, and after logging into my new account, wrong avatar is displayed in right corner (on the bottom of the page "Avatar : " number changes, so I guess something works). Please tell me what you think! Good job ☺️

2023-05-18 15:43 UTC, zuzannapaw commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    setUser(nextUser);
Maybe a good idea would be to move setUser(nextUser) directly under the const nextUser? What do you think?

2023-05-18 15:46 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    setUser(nextUser);
sounds good, I will change it!
As for avatar in top right corner - I don't think it is connected to anything 😅 I forgot it existed, will check how to connect it

2023-05-18 16:23 UTC, mpiwonski commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    setUser(nextUser);
I do agree with @zuzannapaw comments, although good job on task :)

2023-05-18 16:24 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    setUser(nextUser);
@zuzannapaw fixed

2023-05-18 17:28 UTC, zuzannapaw commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    setUser(nextUser);
@wyola Nice, well done! And also I think it's a good idea that avatar is not being displayed when user is not logged in 👍

2023-05-18 17:47 UTC, zuzannapaw approved these changes
Well done with the changes. Now others avatars are visible! 😄  

![image](https://github.com/intive/patronage2023-js/assets/93678778/e41c8f54-7d63-432b-a527-075398ea89ae)

It looks good to me! ✨

2023-05-18 18:28 UTC, wlechowicz requested changes

2023-05-18 18:28 UTC, wlechowicz commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTable.tsx
> +                    data && <Avatar className="avatar" src={data.user.image} />
This is not really correct, is it. If budget is shared with other users, the creators can be other people. So the user data here should come from the data itself, not from the session.

2023-05-18 18:28 UTC, wlechowicz commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    // eslint-disable-next-line turbo/no-undeclared-env-vars
Why?

2023-05-18 18:43 UTC, wyola commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTable.tsx
> +                    data && <Avatar className="avatar" src={data.user.image} />
@wlechowicz I just realized that and changed it back. The problem is that backend does not give us the creator with transaction, so the table controller also takes it from the session right now 👀

2023-05-18 18:44 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    // eslint-disable-next-line turbo/no-undeclared-env-vars
@wlechowicz I admit, I copied it from sign-in and I don't know how to make it work without it 😢

2023-05-18 18:44 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    setUser(nextUser);
hidden it as well

2023-05-18 19:07 UTC, wlechowicz commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTable.tsx
> +                    data && <Avatar className="avatar" src={data.user.image} />
It's a stop-gap measure, better to have it in only one place (controller) that's easy to fix once BE catches up, than in multiple places.

2023-05-18 19:19 UTC, wyola commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTable.tsx
> +                    data && <Avatar className="avatar" src={data.user.image} />
@wlechowicz yes, it is now only in table controller :)

2023-05-18 19:35 UTC, monika-klokosinska-intive commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    // eslint-disable-next-line turbo/no-undeclared-env-vars
@wyola that's weird, it does work in other places in the app without disabling eslint...

2023-05-18 19:44 UTC, monika-klokosinska-intive commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    fetch(env.NEXT_PUBLIC_API_URL + "user/sign-up", {
@wyola  I would go for using `useMutation` from `react-query` since it's what we are using everywhere else in the app. Gonna stay consistent with the approach!

2023-05-18 20:15 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    // eslint-disable-next-line turbo/no-undeclared-env-vars
@monika-klokosinska-intive I will check again tomorrow but I'm pretty sure it was screaming at me 🤔

2023-05-18 21:33 UTC, Vectari approved these changes
I created account, budget and added income. Everything work fine! Great job!

2023-05-19 06:01 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    // eslint-disable-next-line turbo/no-undeclared-env-vars
@monika-klokosinska-intive hmm it works fine 👀 

![awkward](https://github.com/intive/patronage2023-js/assets/80450315/02fcad6e-bd59-41f0-9bfd-6aefd5fdab92)

2023-05-19 07:02 UTC, aniasgit commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    fetch(env.NEXT_PUBLIC_API_URL + "user/sign-up", {
```suggestion
    fetch(`${env.NEXT_PUBLIC_API_URL}user/sign-up`, {
```

2023-05-19 07:08 UTC, aniasgit approved these changes
I agree with @monika-klokosinska-intive that fetch should be as react-query useMutation, but other than that it looks good

2023-05-19 07:10 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    fetch(env.NEXT_PUBLIC_API_URL + "user/sign-up", {
@monika-klokosinska-intive changed

2023-05-19 17:43 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +    fetch(env.NEXT_PUBLIC_API_URL + "user/sign-up", {
@aniasgit changed, without discussed `/` :)

2023-05-19 17:55 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +          throw new Error(response.statusText);
@monika-klokosinska-intive as we discussed, there is a custom error screen at the end of registration process. This is thrown as an error so that `useMutation` knows that `fetch` ended with an error. `response.statusText` is a string like a `bad request`, so there is no point in displaying it. There is nothing specific returned by backend when there is an error (just general "body is not valid"). If you remove this and do:

```
.then(() => {
        throw new Error('test');
 });
```
then you can check that app does not crash like we discussed in the office today :) 
So I think it works fine? 👀

2023-05-22 01:20 UTC, Noshi96 commented
Did BE break something? I couldn't create a user with this data:
```tsx
{
  avatar: "/avatars/4.svg"
  email: "TomaszSobTest@gmail.com"
  firstName: "Tomasz"
  lastName: "ToNiemasz"
  password: "TomaszSobTest@gmail.com"
}
```

2023-05-22 05:30 UTC, AzulloCyll commented
@Noshi96 

```
{
  "avatar": "/avatars/4.svg",
  "email": "TomaszSobTest@gmail.com",
  "firstName": "Tomasz",
  "lastName": "ToNiemasz",
  "password": "Password123!"
}
```
⬆️ 
It was worked.
That code need to be proper JSON format! 
And password => look about our password restrictions in sign-up page.

2023-05-22 05:31 UTC, bdeluga reviewed
LGTM, I'll approve once I will create an account, right now both sign-up and swagger throws 400 at me.

2023-05-22 05:45 UTC, bdeluga approved these changes

2023-05-22 05:54 UTC, AzulloCyll approved these changes
LGTM

2023-05-22 07:24 UTC, monika-klokosinska-intive commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +          throw new Error(response.statusText);
@wyola I would still prefer to display an error, even if it's just a generic one - the infamous "Oooops, something went wrong" will do. We need to give the user some feedback what happened - otherwise they will just be confused.

2023-05-22 08:01 UTC, wyola commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +          throw new Error(response.statusText);
@monika-klokosinska-intive when it happens, this is what user will see. I don't understand what else and where should I display.

<img width="298" alt="image" src="https://github.com/intive/patronage2023-js/assets/80450315/1edcd253-ca68-470e-9c03-d83a8246cb6f">

2023-05-22 08:18 UTC, monika-klokosinska-intive approved these changes

2023-05-22 11:13 UTC, monika-klokosinska-intive commented on apps/web/app/(regflow)/sign-up/SignUp.tsx
> +          throw new Error(response.statusText);
@wyola sorry madam, I got confused which error is erroring when :D

2023-05-23 10:31 UTC, PawelPazderski approved these changes
Added account, logged in 🚀 found myself on the users list in my task 😄 Good job

2023-05-23 19:45 UTC, Noshi96 approved these changes

2023-05-24 14:48 UTC, merged