feat: navigation list and list item #P23-120
intive/patronage2023-js pull request #11
Opened 2023-03-17 16:54 UTC by zuzannapaw

2023-03-18 13:07 UTC, Noshi96 commented on packages/ui/NavList/index.tsx
> +    width:350px;
Consider setting for 100% because the whole list will be placed in the parent component with specified dimensions. Let it fit the parent.

2023-03-18 13:16 UTC, Noshi96 commented on package.json
> +    "material-icons": "^1.13.2",
I think we don't need material-icons anymore, while we use material-symbols. I know there is a problem with displaying icons in the application (localhost: 3000)  to solve it we can set the following code in the layout.tsx file
```javascript
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </head>
```

2023-03-18 13:25 UTC, Noshi96 commented on apps/web/app/Buttons.tsx
> +                <NavItem active={true} key={i++}>
Don't use the index as a key [React Doc](https://react.dev/learn/rendering-lists#why-does-react-need-keys)

2023-03-18 13:31 UTC, Noshi96 commented on packages/ui/NavItem/index.tsx
> +      {active && <ArrowWrapper><Icon icon={"chevron_right"} color="#1E4C40"></Icon></ArrowWrapper>}
I wonder if you need ArrowWrapper when you already have centered content in NavItemStyled

2023-03-18 13:36 UTC, Noshi96 commented on packages/ui/NavItem/index.tsx
> +export const ChildrenWrapper = styled.div`
I would change the name to something more descriptive, e.g., one that you have already used in stories NavItemContent

2023-03-20 08:04 UTC, zuzannapaw commented on packages/ui/NavItem/index.tsx
> +export const ChildrenWrapper = styled.div`
That is a wrapper for incoming children for that component, so i thought "ChildrenWrapper" would work well. Do you mean to change the name that will explicitly tell that word "children" refers to children from component's props?

2023-03-20 08:05 UTC, zuzannapaw commented on packages/ui/NavItem/index.tsx
> +      {active && <ArrowWrapper><Icon icon={"chevron_right"} color="#1E4C40"></Icon></ArrowWrapper>}
I've thought that's a good practice to make wrapper elements for better control, for safety and to always be sure that elements will behave as we want when using flex.

2023-03-20 08:10 UTC, zuzannapaw commented on apps/web/app/Buttons.tsx
> +                <NavItem active={true} key={i++}>
That is a good point.

2023-03-20 12:34 UTC, Alessiass commented on apps/web/app/Buttons.tsx
> +import 'material-icons/iconfont/material-icons.css';
Please remove material-icons from dependancies and imports.

2023-03-20 15:04 UTC, Noshi96 commented on packages/ui/NavItem/index.tsx
> +      {active && <ArrowWrapper><Icon icon={"chevron_right"} color="#1E4C40"></Icon></ArrowWrapper>}
I have encountered the opposite practice, in which we want to limit the use of unnecessary divs, unless we actually need them to set a particular behavior.

2023-03-20 15:26 UTC, Noshi96 commented on packages/ui/NavItem/index.tsx
> +export const ChildrenWrapper = styled.div`
Yes, <ChildrenWrapper> doesn't tell me what the children are. Ofc the children can be anything, but we generally know what they are supposed to be.

2023-03-20 18:12 UTC, zuzannapaw commented on package.json
> +    "material-icons": "^1.13.2",
Thanks, I will delete material-icons from dependencies and imports.

2023-03-20 18:12 UTC, zuzannapaw commented on apps/web/app/Buttons.tsx
> +import 'material-icons/iconfont/material-icons.css';
Thanks, i will delete it.

2023-03-20 18:13 UTC, zuzannapaw commented on packages/ui/NavList/index.tsx
> +    width:350px;
Done.

2023-03-20 18:14 UTC, zuzannapaw commented on apps/web/app/Buttons.tsx
> +                <NavItem active={true} key={i++}>
Done.

2023-03-20 18:38 UTC, zuzannapaw commented on package.json
> +    "material-icons": "^1.13.2",
Done.

2023-03-20 18:38 UTC, zuzannapaw commented on apps/web/app/Buttons.tsx
> +import 'material-icons/iconfont/material-icons.css';
Done.

2023-03-20 18:54 UTC, zuzannapaw commented on packages/ui/NavItem/index.tsx
> +      {active && <ArrowWrapper><Icon icon={"chevron_right"} color="#1E4C40"></Icon></ArrowWrapper>}
I think we need to ask somebody who will help us decide with that 😄

2023-03-21 22:17 UTC, monika-klokosinska-intive commented on apps/web/app/page.tsx
> +//tu bedzie cała aplikacja
@zuzannapaw In English please ;)!

2023-03-21 22:22 UTC, monika-klokosinska-intive commented on apps/web/app/Buttons.tsx
> +}
@zuzannapaw Github is complaining about the lack of a newline at the end of the file and rightfully so, as no newline can mess up some file/text related processes. It's good practice to always end a file with a newline. You don't have to add them manually! If you use Visual Studio Code, you can go to Settings and search for `Insert Final Newline`. When you enable it, VSC will add a newline at the end of file when you save it and you won't have to bother with it.

2023-03-21 22:23 UTC, monika-klokosinska-intive commented on packages/ui/Button/index.tsx
> +
@zuzannapaw Just one newline at the end of file is fine! Please make sure to not add unnecessary white space, it only creates more lines we have to scroll through ;).

2023-03-22 07:58 UTC, zuzannapaw commented on packages/ui/Button/index.tsx
> +
Sorry, i took the code from https://github.com/intive/patronage2023-js for Button. Previously i put my own code inside this component by accident and  in the meantime I had problems with few files. After I realized that , I changed code in Button for the original code.

2023-03-22 08:10 UTC, zuzannapaw commented on apps/web/app/Buttons.tsx
> +}
And sorry again, same situation, the mistakes are because of me messing up the files etc. I put back the original code as well in Buttons.tsx.

2023-03-22 08:13 UTC, monika-klokosinska-intive commented on apps/web/app/Buttons.tsx
> +}
@zuzannapaw Don't apologise! Everybody makes some mess in the code every now and then :D. The important thing is to get in the habit of cleaning it up or setting up tools that will do that for you - it will make your life easier in the long run!

2023-03-22 21:22 UTC, Noshi96 commented on apps/web/app/Buttons.tsx
> +}
@zuzannapaw If you are using VSC, you can check out an extension called Prettier - Code formatter. I really can't remember if I set ```Insert Final Newline``` in VSC, so I'm guessing Prettier includes that as well. You also have automatic formatting on save, so you don't have to worry about tabs and spaces anymore. I saw that we have Prettier mentioned in the readme.md.

2023-03-23 18:52 UTC, monika-klokosinska-intive commented on packages/ui/NavList/index.tsx
> +       {children}
@zuzannapaw Actually **please wait with refactoring everything!** Me and @wlechowicz are still discussing which direction to take this component to, so don't do any premature refactoring! I would hate for you to change something that could have worked fine in the first place ;).

2023-03-27 16:25 UTC, Noshi96 commented on packages/ui/NavList/index.tsx
> +  }
```const contentsCopy = contents.slice();``` is good in terms of immutability of the original data, which is a plus. You can try to use in this particular case js ```.map()``` which also gives you the ability to work on a copy of the data. With ```.map```  you are able to get the same behavior without using ```.find()```, ```.slice()``` and ```.forEach()```

2023-03-28 08:40 UTC, zuzannapaw commented on apps/web/app/Buttons.tsx
> +}
I set `Insert Final Newline` in my VSC settings ☺️  That's a great change!

2023-03-28 08:44 UTC, zuzannapaw commented on packages/ui/NavList/index.tsx
> +  }
Yeah, after some discussion i've completly changed the active dependence for NavItem, now its determined by whether user is on page that has the same path as current NavItem or not☺️  Thanks for the great advice though!

2023-04-05 16:39 UTC, monika-klokosinska-intive commented on packages/ui/NavList/index.tsx
> +  margin-left: 3%;
@zuzannapaw Please don't use percentage values for margins or paddings :).

2023-04-05 17:50 UTC, monika-klokosinska-intive commented on apps/storybook/stories/NavList.stories.tsx
> +import React from "react";
@zuzannapaw You don't have to import `react`!

2023-04-05 17:56 UTC, monika-klokosinska-intive commented on packages/ui/NavList/index.tsx
> +            onClick={() => {}}
@zuzannapaw Is there a reason this is always an empty function? Shouldn't `onClick` be also defined inside the contents array for every object and passed to `NavItem`?

2023-04-06 10:16 UTC, zuzannapaw commented on packages/ui/NavList/index.tsx
> +  margin-left: 3%;
Corrected! 🚀

2023-04-06 10:17 UTC, zuzannapaw commented on apps/storybook/stories/NavList.stories.tsx
> +import React from "react";
Right, deleted!

2023-04-06 10:18 UTC, zuzannapaw commented on packages/ui/NavList/index.tsx
> +            onClick={() => {}}
I believe this onClick stayed there because of previous version, where NavItem wasn't a Link, but Button. I guess now it's not necessary. I removed it for now. :)

2023-04-08 13:02 UTC, monika-klokosinska-intive approved these changes

2023-04-08 16:14 UTC, monika-klokosinska-intive commented on packages/ui/Button/index.tsx
> +
@zuzannapaw Please remove these extra lines and we are good to go ;)

2023-04-10 21:06 UTC, Noshi96 commented on packages/ui/theme.tsx
> +    },
@zuzannapaw I think it was done by mistake here (I think we don't need to have avatarSelecter nested in navList), so just move both objects outside

2023-04-11 10:22 UTC, bdeluga requested changes

2023-04-11 10:22 UTC, bdeluga commented on apps/web/app/css/body.css
There is already global.css defined with styles you provided here, you can remove this file 🗑️ .

2023-04-11 10:22 UTC, bdeluga commented on packages/ui/NavItem/index.tsx
> +import "material-symbols";
Is the line `import 'material-symbols'` needed here? Icon already provides us with this import.

2023-04-11 10:22 UTC, bdeluga commented on packages/ui/NavItem/index.tsx
> +      {active && <Icon icon="chevron_right" color="#1E4C40"></Icon>}
Icon tag could be self-closing e.g. `<Icon/>` but I am just nitpicking, can ignore this one 😅

2023-04-11 10:22 UTC, bdeluga commented on apps/storybook/.storybook/main.cjs
> +
I dont think this extra line is needed here.

2023-04-11 10:28 UTC, zuzannapaw commented on packages/ui/Button/index.tsx
> +
@monika-klokosinska-intive thank you, it's done :)

2023-04-11 10:28 UTC, zuzannapaw commented on packages/ui/theme.tsx
> +    },
done:) thanks again

2023-04-11 10:28 UTC, zuzannapaw commented on packages/ui/package.json
> +    "material-symbols": "^0.5.1",
@Noshi96 done :) !

2023-04-11 10:29 UTC, zuzannapaw commented on apps/web/app/css/body.css
Thank you for all your remarks, I believe I have applied all of them :)

2023-04-11 10:29 UTC, zuzannapaw commented on packages/ui/NavItem/index.tsx
> +      {active && <Icon icon="chevron_right" color="#1E4C40"></Icon>}
@bdeluga  you are totally right! I changed it :)

2023-04-11 12:09 UTC, aniasgit commented on packages/ui/Button/index.tsx
> +`;
add new line here

2023-04-11 19:17 UTC, monika-klokosinska-intive commented on packages/ui/Button/index.tsx
> +`;
@zuzannapaw take a look at @aniasgit's comment :).

2023-04-12 05:25 UTC, bdeluga approved these changes
🚀

2023-04-12 09:52 UTC, zuzannapaw commented on packages/ui/Button/index.tsx
> +`;
done :)

2023-04-12 09:53 UTC, merged