feat: favourite budgets #P23-36
intive/patronage2023-js pull request #112
Opened 2023-05-23 19:19 UTC by zuzannapaw

<h1> Adding budgets to favourites available ❤️ </h1>

<h2> Overview 👀 </h2>

- When user is on budget page, heart is being replaced by active arrow in budget's list, according to design,

- User can add budget to favourites by clicking on heart icon, as well as he can delete it,

-  When clicking on heart icon, it is being automatically filled or outlined.  Whereas in the case, when something went wrong and update was impossible, heart icon comes back to it's previous state.    

<h2> Adjustement ✨ </h2>

- Added aria-label for accessibility, text depend on component's state, updated dictionary. 

```javascript
ariaLabel = isFavourite ? t(dict.unfavourite) : t(dict.favourite);
```

2023-05-23 20:13 UTC, wlechowicz requested changes

2023-05-23 20:13 UTC, wlechowicz commented on apps/web/app/(navigation)/Favourite.tsx
> +let ariaLabel;
Nono.

2023-05-23 20:13 UTC, wlechowicz commented on apps/web/app/(navigation)/Favourite.tsx
> +    setIsFetching(true);
Why is this done through an effect, rather than just calling fetch right here and doing what it does now - updating state in .then?

2023-05-23 20:13 UTC, wlechowicz commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +import {Favourite} from "./Favourite"
Formatting

2023-05-23 20:13 UTC, wlechowicz commented on apps/web/services/mutations.ts
> +  isFavourite: boolean;
🍵 > 🍔 ?

2023-05-24 07:53 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +    setIsFetching(true);
@wlechowicz  It was created because if the heart needs to be changed immidietaly, I change it by useState and only after that I allow request's sending. Now it works like optimistic update, and if there is any 400 or 401 error, the heart is being  indeed filled/unfilled immidietaly , but after a second it goes back to it's previous state. I alo used useEffect because when I wasn't using it, it didn't work correctly (change of state was too late for pass it to the fetch function as you said). As well without isFetching , in the case with potential errors, it was just a dance of hearts filling and unfilling themselfs 💃 . So now heart is being changed straight away, if request was successful, it stays, but if it failed, it goes back to previous state.

2023-05-24 09:11 UTC, zuzannapaw commented on apps/web/services/mutations.ts
> +  isFavourite: boolean;
@wlechowicz  after some time with solving this cipher i must tell that I changed "Favorite" to "Favourite" because we are getting an UK version from backend, so I thought it will be better to adapt it. 👀

2023-05-24 09:32 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +    setIsFetching(true);
@wlechowicz but of course I will refactor it if it's necessary

2023-05-24 09:38 UTC, aniasgit commented on apps/web/app/(navigation)/Favourite.tsx
> +      fetch(
fetch should be changed to superfetch ;)

2023-05-24 09:45 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/Favourite.tsx
> +  ariaLabel = isFavourite ? t(dict.unfavourite) : t(dict.favourite);
@zuzannapaw you can define `ariaLabel` here as const and you should be fine!

2023-05-24 09:48 UTC, monika-klokosinska-intive requested changes
@zuzannapaw `isFetching` and the `useEffect` related to it add an unnecessary complexity to the flow. Please follow @wlechowicz to simplify it.

2023-05-24 17:02 UTC, wyola commented on apps/web/app/(navigation)/Favourite.tsx
> +const Wrapper = styled.div<Active>`
this should button, because right now it is not accessible with the keyboard

```suggestion
const Wrapper = styled.button<Active>`
```
Once you change it to `button` then you can access it and switch on/off with keyboard. There is some additional styling needed to get rid of default button styles.

https://github.com/intive/patronage2023-js/assets/80450315/60fe06f3-a05a-480c-845f-24ed29fa7100

2023-05-24 22:03 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +let ariaLabel;
@wlechowicz fixed

2023-05-24 22:03 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +    setIsFetching(true);
@wlechowicz I deleted useEffect

2023-05-24 22:04 UTC, zuzannapaw commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +import {Favourite} from "./Favourite"
@wlechowicz fixed

2023-05-24 22:06 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +      fetch(
@aniasgit  I will change it with new amendments 👍  thank you

2023-05-24 22:06 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +const Wrapper = styled.div<Active>`
@wyola thank you for your comment, I changed that

2023-05-24 22:47 UTC, mpiwonski approved these changes
Good job :)

2023-05-24 23:05 UTC, bdeluga commented on apps/web/app/(navigation)/Favourite.tsx
> +  };
I belive this should be useSuperfetch 🚀 
Also remember, `status -> httpStatus` in superFetch.

2023-05-24 23:11 UTC, Vectari reviewed
I think it not work correct now:
1. I add budget to favourite and i have red heart.
2. With budgets list still open i open other budget.
3. I open budgets list and i dont see red heart on my favourite budget.
4. I have to open "reports" or change tabs in browser with closed "budgets" to see red heart on favourite budget.

Maybe "invalidateQueries"  after add to favourite will help?

2023-05-25 08:16 UTC, aniasgit commented on apps/web/app/(navigation)/Favourite.tsx
> +    fetch(
I belive we can use our superfetch here.

2023-05-25 08:25 UTC, aniasgit commented on apps/web/app/(navigation)/Favourite.tsx
> +      fetch(
@zuzannapaw you moved the fetch to a different location, but it's still not a superfetch

2023-05-25 08:28 UTC, aniasgit reviewed
I like how it works now, but I think you need to change fetch to superfetch :) And there are some prettier problems again :/

2023-05-25 09:06 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +      fetch(
@aniasgit  Yes, as I said in previous comment I will change it, I havn't changed it yet. It will be fixed ☺️

2023-05-25 09:07 UTC, zuzannapaw reviewed
@Vectari  thank you for your comment, this problem has been fixed 🚀

2023-05-25 09:08 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +  };
@bdeluga Yes you are right, I will change it

2023-05-25 10:31 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +      fetch(
@aniasgit I has been fixed ☺️

2023-05-25 10:31 UTC, zuzannapaw commented on apps/web/app/(navigation)/Favourite.tsx
> +  };
@bdeluga changed!

2023-05-25 10:35 UTC, wyola approved these changes
LGTM ❤️

2023-05-25 10:41 UTC, Vectari approved these changes
Good job 👏

2023-05-25 11:45 UTC, PawelPazderski commented
> @PawelPazderski maybe you are a bit right 😅 but that was the color wanted by our client 🤔

Oh - was it? I must have missed that, in that case I LOVE IT 😅

2023-05-25 11:46 UTC, PawelPazderski approved these changes

2023-05-25 12:42 UTC, wlechowicz approved these changes

2023-05-25 12:44 UTC, monika-klokosinska-intive approved these changes

2023-05-25 12:46 UTC, merged

2023-05-25 12:47 UTC, Noshi96 approved these changes
Everything works well, great job! 🚀  Here are some suggestions that can be omitted

2023-05-25 12:47 UTC, Noshi96 commented on apps/web/app/(navigation)/Favourite.tsx
> +      }
```suggestion
  const setFavHandler = (event: React.MouseEvent<HTMLElement>) => {
    //to prevent relocating
    event.preventDefault();
    //to prevent closing budget's list
    event.stopPropagation();

    const newIsFavouriteState = !isFavourite;
    setIsFavourite(newIsFavouriteState);

    fetch(
      `${env.NEXT_PUBLIC_API_URL}/budgets/${budgetId}/favourite?isFavourite=${newIsFavouriteState}`,
      {
        method: "PUT",
      }
```

I see you noticed that we don't have access to the current isFavourite immediately after using setIsFavourite. So to make it more readable, what do you think about adding an extra const with the current state of isFavourite?