feat: input component #P23-117
intive/patronage2023-js pull request #12
Opened 2023-03-18 17:38 UTC by wyola

2023-03-20 01:15 UTC, bdeluga requested changes

2023-03-20 01:15 UTC, bdeluga commented on packages/ui/Input/index.tsx
> +        }}
```suggestion
onChange={onChange}
```
Someone that uses this input probably knows how he need to handle onChange. Let's just pass their function instead.🚀

2023-03-20 01:15 UTC, bdeluga commented on packages/ui/Input/index.tsx
> +      );
```suggestion
return (
<StyledIcon
         onClick={() => {
            setPasswordShown(!passwordShown)
            inputRef.current?.focus()
          }}
        >
          <Icon
            icon={`${passwordShown ? 'visibility_off' : 'visibility'}`}
            color="#49454f"
            iconSize={23}
          />
</StyledIcon>
)
```
This code works great, but i think you overdid it. What would you say we cut this code in half ? ✂️ 
Of course we have to remember to change how we handle Input type with this change

2023-03-20 08:56 UTC, wyola commented on packages/ui/Input/index.tsx
> +      );
Thanks, I did this change, just slightly different on one line, since typescript was mad 😅

2023-03-20 08:58 UTC, wyola commented on packages/ui/Input/index.tsx
> +} & React.HTMLProps<HTMLDivElement>;
thanks for that, I changed the code

2023-03-20 08:59 UTC, wyola commented on packages/ui/Input/index.tsx
> +import * as React from "react";
I was importing it like this, since I was using it as well with things like `React.HTMLProps<HTMLInputElement>` etc. but after changing those parts of code according to your other remarks, I can also change this one 🫡

2023-03-20 12:09 UTC, wyola commented on packages/ui/Input/index.tsx
> +      </StyledSupportingLabel>
I changed it, but this `<StyledSupportingLabel hasError>` has to be like this `<StyledSupportingLabel hasError={hasError}>` because otherwise it would always be true and display red supporting label :) 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/80450315/226334653-7c4e0a09-77b7-4313-a023-c53dfec254bd.png">

but thank you for pointing this out in general, because I got so focused on this supporting label that indeed I forgot that there are inputs without it :)

2023-03-20 12:47 UTC, wyola commented on packages/ui/Input/index.tsx
> +            }
it accepts only strings, which is defined in props `onChange?: (newValue: string) => void;`

2023-03-21 15:52 UTC, Noshi96 commented on packages/ui/Input/index.tsx
> +  const [typeOverride, setTypeOverride] = useState("");
If your useState only takes two values ("" and "text"), can it be a boolean type?

2023-03-21 21:42 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +export type InputProps = {
@wyola You use `InputProps` in line 14, but define it here. The code would be more readable if `InputProps` were defined before its first usage.

2023-03-21 21:55 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +            onChange(event.target.value);
@wyola I would pass the whole event to `onChange`. You don't know what the passed function needs from the the event and it's not really the concern of this component. The function can then extract what it needs from the event and use it, but that's outside the scope of responsibility for the input.

2023-03-21 21:56 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +            onChange(event.target.value);
@wyola 
```
 if (onChange) {
            onChange(event);
 ```

2023-03-21 22:06 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +      border-color: #b3261e !important;
`!important` is very bad, not good, terrible practice. What is the reason for it here?

2023-03-21 22:15 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +  onChange?: (newValue: string) => void;
@wyola how about `onChange?: React.ChangeEventHandler<HTMLInputElement>`. This way it's still typed, but still allows for more freedom in how the function will be built (see my other comments concerning `onChange`)

2023-03-22 15:33 UTC, wyola commented on packages/ui/Input/index.tsx
> +  const [typeOverride, setTypeOverride] = useState("");
@Noshi96  it could be, it's a possibility, but in my opinion, it does not change much

2023-03-22 15:53 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +      border-color: #b3261e !important;
@wyola `!important` should always be the last resort after everything else failed. Otherwise it gets over-used and before you know, half of your css rules have `!important` in them. Overwriting them then (if you need to) becomes impossible without sticking more `!important`... and you can probably see where it is going.
It's a useful tool in case some extreme cases, but shouldn't be the first thing you reach for.

2023-03-22 16:25 UTC, wyola commented on packages/ui/Input/index.tsx
> +      border-color: #b3261e !important;
@monika-klokosinska-intive ok, I fixed it, will push it soon with other changes

2023-03-22 17:36 UTC, wyola commented on packages/ui/Input/index.tsx
> +  React.HTMLProps<HTMLInputElement>;
@monika-klokosinska-intive @wlechowicz should I limit the props from input element only to those that are used by the component? https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys

it could look like this:
```suggestion
  Pick<React.HTMLProps<HTMLInputElement>, 'id' | 'type' | 'value'>;
```

2023-03-22 20:19 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +  React.HTMLProps<HTMLInputElement>;
@wyola either way is fine with me! @wlechowicz what do you think?

2023-03-22 20:36 UTC, monika-klokosinska-intive commented on packages/ui/Input/index.tsx
> +            icon={`${typeOverride ? "visibility_off" : "visibility"}`}
@wyola you can achieve the same thing with simpler code e.g ` icon={typeOverride ? "visibility_off" : "visibility"`.

2023-03-22 20:38 UTC, monika-klokosinska-intive commented
@wyola Great job on all the changes in PR! 
Looks like you have a conflict in `packages/ui/index.tsx` - please merge the main branch to yours and resolve it.

2023-03-22 22:21 UTC, wyola commented
> @wyola Great job on all the changes in PR! Looks like you have a conflict in `packages/ui/index.tsx` - please merge the main branch to yours and resolve it.

@monika-klokosinska-intive thank you! I merged it and resolved the conflict. One of the checks fails and I can't seem to find why (it was fine before)

<img width="479" alt="image" src="https://user-images.githubusercontent.com/80450315/227051238-6b199aab-3d57-4cf5-8f33-cb5ac1865a56.png">

2023-03-23 06:50 UTC, AzulloCyll approved these changes
I think it's good to merge.

2023-03-23 12:10 UTC, wyola commented on packages/ui/Input/index.tsx
> +          <Icon icon="add_circle" color="#49454f" iconSize={20} />
@aniasgit you are right of course, I was trying to find this icon with "close" and "x", did not think to type "cancel" 😂 🤦🏻‍♀️will change it now

2023-03-23 12:21 UTC, wyola commented
> > @wyola Great job on all the changes in PR! Looks like you have a conflict in `packages/ui/index.tsx` - please merge the main branch to yours and resolve it.
> 
> @monika-klokosinska-intive thank you! I merged it and resolved the conflict. One of the checks fails and I can't seem to find why (it was fine before)
> 
> <img alt="image" width="479" src="https://user-images.githubusercontent.com/80450315/227051238-6b199aab-3d57-4cf5-8f33-cb5ac1865a56.png">

nvm, I fixed it (it was missing "use client" and web build was failing)

2023-03-23 12:51 UTC, Noshi96 commented on packages/ui/Input/index.tsx
Input component does not match the design (padding and green icon)
![image](https://user-images.githubusercontent.com/38572172/227209364-09d3577a-b97a-4fb0-8201-f92abda84295.png)

2023-03-23 13:05 UTC, wyola commented on packages/ui/Input/index.tsx
@Noshi96 what you are showing there is distance to line height, but nevertheless you are right and padding should be 20px top and bottom and 16px left 
<img width="184" alt="image" src="https://user-images.githubusercontent.com/80450315/227212952-6b64eae6-a9af-420a-ba71-e2e6216c79f0.png">

2023-03-23 13:43 UTC, wyola commented on packages/ui/Input/index.tsx
@Noshi96 I corrected it, changed CSS a bit to include line height to be 150% of a font size and padding to be 14px (since 16px is together with the 2px border in the design).

Good catch btw!

2023-03-23 14:28 UTC, PawelPazderski commented
Can we pls add (optional) onFocus to the input? I'll need it in Log In form to close the error message for sure.

2023-03-23 14:52 UTC, bdeluga commented
> Can we pls add (optional) onFocus to the input? I'll need it in Log In form to close the error message for sure.

It alread has optional onFocus since it extends normal input right ?
![image](https://user-images.githubusercontent.com/79754698/227242101-b86ac73f-ef88-485c-a2f6-2f8a54de7de8.png)

2023-03-23 15:04 UTC, bdeluga commented
Like i did above ?

2023-03-23 15:05 UTC, PawelPazderski commented
> Like i did above ?

Yep, got this:
![image](https://user-images.githubusercontent.com/72406958/227246081-60b2a2eb-18ef-4d38-bfe9-020330761f40.png)

2023-03-23 15:06 UTC, bdeluga commented
Hmm, did you added "use client"

2023-03-23 15:07 UTC, PawelPazderski commented
> Hmm, did you added "use client"

Yes, go use client I test it in the "Buttons"
![image](https://user-images.githubusercontent.com/72406958/227246749-4214e0eb-e11f-4fa4-8cf1-b25d68bff68d.png)

2023-03-23 15:12 UTC, PawelPazderski commented
> So is it working, cause I got confused right now haha 😅

It's not on my side, if the onFocus is not added to props

2023-03-23 15:39 UTC, bdeluga commented
I downloaded commit with onFocus that Ola already added. (no wonder it was working 😅 ) Silly me forgot we aren't passing all props `{...props}` sorry for confuse. @PawelPazderski  is 100% right onFocus is needed.

2023-03-23 16:38 UTC, PawelPazderski approved these changes
Looks good works fine to me now :)

2023-03-28 12:47 UTC, merged