feat: sign-out #P23-19
intive/patronage2023-js pull request #123
Opened 2023-05-28 10:11 UTC by AzulloCyll

2023-05-28 16:04 UTC, wyola reviewed
Good idea with the `sign out` option, it was missing in the app! Few remarks from me

2023-05-28 16:04 UTC, wyola commented on apps/web/app/(navigation)/MainMenu.tsx
> +  };
You don't need `router.push("/")` here, because it is handled by `next-auth` here:

https://github.com/intive/patronage2023-js/blob/5609f071eb22fb050e9fcf7ca8a1b84d67e84e6c/apps/web/pages/api/auth/%5B...nextauth%5D.ts#L83

if you also remove the `home` option then you don't need both `router.push("/")`

```suggestion
  const menuHandler = (value: string) => {
    if (value === "sign-out") {
      signOut();
    }
  };

2023-05-28 16:11 UTC, bdeluga reviewed
I feel like this could simply be a dropdown, which renders `Link` with `href="/"`  and a button with `signOut` on click. @zuzannapaw already provided us with TransactionDropdownMenu. You could just make it more generic to render main item `avatar` in this case and just toss said components to it's props.

@monika-klokosinska-intive  @wlechowicz  what do you guys think ? 

Great work nontheless, it is working as expected 🚀

2023-05-28 16:11 UTC, bdeluga commented on apps/web/app/(navigation)/MainMenu.tsx
> +      signOut();
SignOut, "pushes" you to "/" on it's own, dont need to `router.push("/")`

2023-05-28 19:47 UTC, zuzannapaw reviewed
What a great improvement be to be able to log out from any page now! ✨ 

Only few things from me.  @bdeluga and @wyola proposed very apt suggestion about `router.push()` 👀 

Well done 🚀 
PS. As we said before, I let myself commit from your branch one amendment of french text 🐸

2023-05-28 19:47 UTC, zuzannapaw commented on apps/web/app/(navigation)/MainMenu.tsx
> +                ))}
You could use object's destructuring here 
```suggestion
                {items.map(({value, text}) => (
                  <SelectItemStyled value={value} key={value}>
                    <Select.ItemText>{text}</Select.ItemText>
                  </SelectItemStyled>
                ))}
```

2023-05-28 19:47 UTC, zuzannapaw commented on apps/web/app/(navigation)/MainMenu.tsx
> +import { useTranslate } from "lib/hooks";
I suggest to place external imports first, and after that our internal imports

2023-05-28 19:47 UTC, zuzannapaw commented on apps/web/app/(navigation)/MainMenu.tsx
> +    },
I agree with @wyola, I believe it's reduntant

2023-05-29 12:22 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +    },
Home was added, like a placeholder. To show that's in that select we can have more than one options. Also select with only one option looks radicolous. :P

2023-05-29 12:29 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +              <AvatarStyled src="avatars/3.svg" outlined />
Ooo. Thank you to paying attention to it. I'am restoring it.

2023-05-29 12:31 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +        <Select.Root onValueChange={(value) => menuHandler(value)}>
I need this value on handler, because I decided not to delete "Home" option flrom select menu

2023-05-29 12:35 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +  };
You right, I don't need router.push on sign-out route, but i'm leaving another one to make "Home button work"

2023-05-29 12:36 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +      signOut();
I used select, brecause i've styles for other select written already, and I tried to make both select's looks similar.

2023-05-29 12:40 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +                ))}
That's good sugestion :)

2023-05-29 12:41 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +import { useTranslate } from "lib/hooks";
Ok, I'll do it.

2023-05-29 13:36 UTC, Alessiass requested changes

2023-05-29 13:36 UTC, Alessiass commented on apps/web/app/(navigation)/MainMenu.tsx
> +  };
```suggestion
  const menuHandler = (value: string) => {
    value === "sign-out" ? signOut() : "";
  };
  };
```

The signOut function already has redirect function built in thus push will never fire. This can be simplified since you cannot access this menu if you are not logged in already.

2023-05-29 14:16 UTC, Alessiass approved these changes

2023-05-29 14:30 UTC, wyola commented on apps/web/app/(navigation)/MainMenu.tsx
> +    },
@AzulloCyll to me personally it looks more ridiculous to have "home" there ;D I don't see anything strange in having there just the sign out. But that's just my personal preference, keep it as you wish 🤗

2023-05-29 14:55 UTC, wyola commented on apps/web/app/(navigation)/MainMenu.tsx
> +        <Select.Root onValueChange={(value) => menuHandler(value)}>
@AzulloCyll with suggested approach the `value` will still be passed to the `menuHandler` :)

2023-05-29 19:36 UTC, Noshi96 commented on apps/web/app/(navigation)/MainMenu.tsx
> +        </Select.Root>
Do we need radix select here? Isn't it better to use radix dropdown? What do you think?

2023-05-29 19:49 UTC, Noshi96 reviewed
I also agree with @zuzannapaw that we need some sort of indicator to show the user that they can interact with the avatar. Other than that, good job as the logout works as it should 🚀

2023-05-30 06:43 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +        </Select.Root>
I really really don't know. I've used select because I'v had all the styles already written, so ive decided to do it on select. 🤔

2023-05-30 06:44 UTC, AzulloCyll commented
> I also agree with @zuzannapaw that we need some sort of indicator to show the user that they can interact with the avatar. Other than that, good job as the logout works as it should 🚀

I've added indicator :)

2023-05-30 06:44 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +                ))}
I've added arrow indicator also.

2023-05-30 09:42 UTC, PawelPazderski reviewed
Looks nice but ran into unexpected behaviour, as a user I expect to log out from any place in the app and it should redirect me to login page, meanwhile it doesn't happen so everywhere 👇 

https://github.com/intive/patronage2023-js/assets/72406958/4fe957c9-b603-4b30-ab43-83da527ee424

2023-05-30 09:54 UTC, AzulloCyll commented
> Looks nice but ran into unexpected behaviour, as a user I expect to log out from any place in the app and it should redirect me to login page, meanwhile it doesn't happen so everywhere 👇

I know about it. 👌🏻 
In PR with refiment from @bdeluga there will be no left menu for unlogged user, so we will always be redirected to sign-in page. So if we merge it the behavior will be correct :)

It's beahavior is as is because that path is no protected by middleware. (That's was a cause why I've added router.push("/") originally too).

2023-05-30 10:42 UTC, wyola requested changes
found a bug 🐛

2023-05-30 10:42 UTC, wyola commented on apps/web/app/(navigation)/MainMenu.tsx
> +          onValueChange={(value) => menuHandler(value)}
I am pointing that one out again ;-) `menuHandler` is already a function that takes `value`

```suggestion
          onValueChange={menuHandler}
```
but I worked out that there is an issue anyway. With the way you have it right now, redirecting to `home` works only the first time. After that, `select` "remembers" the previously chosen value and does not call `onValueChange`.

check this with the current code that you have: 
- login
- stay on the home page or go the budget page
- select `home` from your select
- page reloads correctly
- go to other budget page or stay on home and select home again - page does not reload anymore

How to fix it? add `value=""` in `Select.Root`
```
        <Select.Root
          value=""
          onValueChange={menuHandler}
```
... and please include the suggested change, since it is really the same :)

2023-05-30 10:53 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +          onValueChange={(value) => menuHandler(value)}
Oooo! Youre right, that is wierd. I'll fix it.

2023-05-30 11:02 UTC, AzulloCyll commented on apps/web/app/(navigation)/MainMenu.tsx
> +        <Select.Root onValueChange={(value) => menuHandler(value)}>
fixed

2023-05-30 14:57 UTC, monika-klokosinska-intive approved these changes

2023-05-30 15:01 UTC, wyola approved these changes

2023-05-30 15:18 UTC, merged