fix: budget list search #P23-375
intive/patronage2023-js pull request #124
Opened 2023-05-28 12:45 UTC by Vectari

# Hello! 👋
Task [Fix Budget List Search](https://tracker.intive.com/jira/browse/PATRO23-375)

## What fixes:
1. Now when you type something in search bar and change tab (e.g. Reports) and open Budgets again, search bar will be empty and budget list will show all budgets.
2. When you go to specyfic budget after search and then open again budget list, search bar again will be empty and budget list will show all budgets.

2023-05-28 13:17 UTC, Noshi96 requested changes
Works well! Minor suggestions below

2023-05-28 13:17 UTC, Noshi96 commented on packages/ui/SideNavigationBar/index.tsx
>    };
Here, when you reset it after opening the submenu, you force an additional request and refresh the list, but the search state is the same (empty string). Setting `resetSearch();` in `hideSubMenu()` I think is enough. Or is there some other use case that I don't see?
```suggestion
    setSubMenuId(id);
    resetIsNavListItemClicked();
    setIsSubMenuShown(true);
  };
```

2023-05-28 13:26 UTC, Vectari commented on packages/ui/SideNavigationBar/index.tsx
>    };
I use it to refresh budget list when you are in specific budget after search. Number 2 in my PR describe.

2023-05-28 13:28 UTC, Vectari commented on apps/web/app/(navigation)/SideNavigationBar.tsx
>      },
You are right. Fixed :)

2023-05-28 13:53 UTC, Noshi96 commented on packages/ui/SideNavigationBar/index.tsx
>    };
Okay now I see, my mistake :)
I'm still wondering, because when you reopen after changing the budget for a second, you will see the old searched budget 🤔

2023-05-28 13:59 UTC, Vectari commented on packages/ui/SideNavigationBar/index.tsx
>    };
Probably debounce. I’ll try to do something with it

2023-05-28 14:02 UTC, Noshi96 commented on packages/ui/SideNavigationBar/index.tsx
>    };
Previously, when the cleanup worked, there was a useEffect in the SubMenu/index.tsx file that called onChange on the input with an empty string when the component was unmounted. I'm not sure if this was the best solution:
```tsx
  useEffect(() => {
    return () => {
      searchInput?.onChange?.("");
    };
  }, []);
```

2023-05-28 14:08 UTC, Vectari commented on packages/ui/SideNavigationBar/index.tsx
>    };
Yes but with it there was ESlint warning and probably (I don't really remember) it don't work in case described in number 2 in PR description.

2023-05-28 14:22 UTC, Noshi96 commented on packages/ui/SideNavigationBar/index.tsx
>    };
It works, but you are right about the ESlint warning caused by the empty dependency array in useEffect.

2023-05-28 15:38 UTC, wyola approved these changes
just one minor thing from me, other than that works good!

2023-05-28 15:38 UTC, wyola commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +        resetSearch={setSearchValue}
You are calling a function without a parameter, which causes setting this state to `undefined`, while it should be of a `string` type. Doesn't seem to break anything, but let's be on the safe side and have the proper type 🤓 

```suggestion
        resetSearch={() => searchValue("")}
```

<img width="947" alt="search1" src="https://github.com/intive/patronage2023-js/assets/80450315/e548860d-8e57-4bd2-808b-8a2204129471">

after closing the side nav, the state is `undefined` ⬇️ 

<img width="957" alt="search2" src="https://github.com/intive/patronage2023-js/assets/80450315/0ce13db7-7621-42ed-8bac-2b7434ebd4ad">

2023-05-29 01:11 UTC, AzulloCyll approved these changes

2023-05-29 10:27 UTC, zuzannapaw approved these changes
Works smoothly! 🚀

2023-05-29 12:24 UTC, Noshi96 approved these changes

2023-05-29 18:00 UTC, Alessiass approved these changes

2023-05-29 22:12 UTC, Vectari commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +        resetSearch={setSearchValue}
Great idea. Fixed 🙂

2023-05-30 09:22 UTC, PawelPazderski approved these changes
Works as it should, nice. Only one tiny little thing it's not some major problem just cought my eye - when we search the budget - go into the searched one and then open the list again we can see the filtered list for a slight moment before the list loads again, other than that 🎸 🚀

2023-05-30 14:50 UTC, monika-klokosinska-intive approved these changes

2023-05-30 16:20 UTC, merged