refactor: App refinement #P23-374
intive/patronage2023-js pull request #125
Opened 2023-05-28 16:34 UTC by bdeluga

# Overview 📖 
This refactor was undertaken due to the end of patronage and preparations for a demo. Here's a list:
- Removed mocks for budgets and transactions
- Merged two `types` folders into one placing it in `/lib`
- Components depending on more than 2 components were placed into folder with all of their imports.
- Moved default avatar src into `/avatars/default.svg`
- Moved validate functions `fixCurrencyObject.ts`,`iconValidation.ts`,`useValidateBudgetModal.tsx` into `lib/validations`
- Moved `Navbar` and `SideNavigationBar` to components 
- Changed `settings` page from `[...catchAll]` to correspoiding sub folders with their corresponding components
- Now when not logged you will be manually redirected to `sign-in` page (change [accepted ](https://intive-apu8934.slack.com/archives/C04R6LM4JSV/p1685285364110079)by client)

### That's the full list so you don't have to scroll and check all of those 72 files :sparkles:

## Possible upgrade
There are still a lot of components that doesn't use superFetch, I can also refactor them if needed. 🚀 

### Concerns
I don't know how this PR will affect others work, and here's the question for leaders @wlechowicz @monika-klokosinska-intive. Should this be merged first or last in this sprint. I can pull main to this branch and resolve any conflicts there will be.

2023-05-28 16:51 UTC, wyola requested changes

2023-05-28 16:51 UTC, wyola commented on apps/storybook/stories/NavList.stories.tsx
> +          <Icon icon="payments" color="#1E4C40" />
please use theme

(I just refuse to accept this PR until my opened PR is merged xD)

2023-05-28 17:07 UTC, bdeluga commented on apps/storybook/stories/NavList.stories.tsx
> +          <Icon icon="payments" color="#1E4C40" />
Is it even as possible as inline color  in storybook  ?

2023-05-28 17:08 UTC, wyola commented on apps/storybook/stories/NavList.stories.tsx
> +          <Icon icon="payments" color="#1E4C40" />
Idk, it's a tactical move

2023-05-28 17:22 UTC, wyola approved these changes

2023-05-28 20:37 UTC, zuzannapaw approved these changes
Remarkable work! 🚀 Thank you so much for indicating places in dictionary for me, I completed it!🐸

2023-05-29 08:58 UTC, PawelPazderski approved these changes
Good job 🚀 I admire your patience and meticulousness!

2023-05-29 13:27 UTC, Alessiass approved these changes
Well done, I sense many conflicts to be resolved before the demo 🚀

2023-05-29 20:37 UTC, Noshi96 approved these changes
Great job on adjusting the folder structure, now it looks professional and clean 😎

2023-05-29 22:49 UTC, Vectari approved these changes
Great job! 🚀

2023-05-30 16:08 UTC, wlechowicz approved these changes
Good job.
Have fun resolving conflicts! There's already plenty, so it would be best to resolve it all here, merge this ASAP and then there should be limited changes required in each of the open PRs.

2023-05-31 12:28 UTC, AzulloCyll approved these changes
Great work! 🚀

2023-05-31 19:34 UTC, wlechowicz approved these changes
Must have been heaps of fun.

2023-05-31 21:34 UTC, Noshi96 reviewed
Something is wrong when logging in, it doesn't redirect me to the home/main page. The requests seem to work correctly. And after going directly to "/" by changing the URL, I can see that I am logged in.

2023-06-01 05:58 UTC, bdeluga commented
> Something is wrong when logging in, it doesn't redirect me to the home/main page. The requests seem to work correctly. And after going directly to "/" by changing the URL, I can see that I am logged in.

Actually it redirects me  to `/` after login properly.

2023-06-01 05:59 UTC, merged