feat: mobile view category filtering #P23-365
intive/patronage2023-js pull request #128
Opened 2023-05-29 17:55 UTC by Alessiass

## Before ☎️ 
When layout switches to mobile category selector disappears and user is unable to add or remove existing filters.

## After 📱
After switching to mobile, accordion apears that allows the user to modify filters.
![image](https://github.com/intive/patronage2023-js/assets/94013800/f19f28e9-a9a7-454d-8ac7-7767a2ecd951)
Accordion is created as reusable component and is available in storybook for preview.

## To be done 🗒️ 
Currently modal for managing categories is not prepared and needs to be implemented later on.

2023-05-29 22:01 UTC, Noshi96 requested changes
I like this new feature, it was definitely needed! I think a better place for the management button would be the top of the list, because what if we have 40 or more categories. In that scenario, the user has to scroll a lot to get to those settings. I would also make the management button smaller. Below is my suggestion. Other than that and some minor tweaks, it works great! 🚀 

![image](https://github.com/intive/patronage2023-js/assets/38572172/5f458f94-d5a3-4ec6-8112-9f239db8f49e)

2023-05-29 22:46 UTC, Vectari approved these changes
Great work! 🚀
Maybe only one suggestion to get rid of that white space on tablet. What do you think?
![365](https://github.com/intive/patronage2023-js/assets/93955642/3b75c13c-bfc6-4826-b5ee-0bc6e457e8a7)

2023-05-30 09:13 UTC, PawelPazderski reviewed
Great work, please take a look at issue here - I noticed that if there are some categories selected and the window size changes to the mobile view no categories are selected on the list 👇 

https://github.com/intive/patronage2023-js/assets/72406958/ec55947d-e14f-43c6-ad23-919d237f4050

2023-05-30 14:29 UTC, wyola reviewed
Great addition to the app! ⭐ Two things from me

2023-05-30 14:29 UTC, wyola commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +      <MobileCategorySearch />
I would put it inside the `FilterSearchWrapper`, between the button group and the search. Right now, you put it outside the wrapper, hence Card's gap comes in between the search and the accordion, so the spacing looks not great:

![image](https://github.com/intive/patronage2023-js/assets/80450315/3689d2f0-3918-414c-baf6-3c8d0b299fe1)

while after the change: 

![image](https://github.com/intive/patronage2023-js/assets/80450315/8d3b1a0d-805e-4215-b37e-8e3b7bc3e0bb)

Another thing I suggest is to change accordion's inactive border to have the same shade of grey as the search and button group have

2023-05-30 14:43 UTC, Alessiass commented on packages/ui/Accordion/Accordion.styles.tsx
> +    </AccordionHeader>
This was made from RadixUI template.

2023-05-30 14:54 UTC, Alessiass commented on packages/ui/Accordion/Accordion.styles.tsx
> +import * as Accordion from "@radix-ui/react-accordion";
I was thinking about it, but if some functionalities would be missing later on it would be easier to extend them with RadixUI. Also it provides a lot of cool functionalities out of the hat that we don't need to think about later on, e.g. one item open at a time. Valid question 🚀

2023-05-30 15:37 UTC, Alessiass commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +      <MobileCategorySearch />
I've moved the categories to wrapper and changed colors but I've left it on the bottom since opening it moves the table down, it would be nice if the searchbar will remain in place for the whole search/filter section.

2023-05-30 16:26 UTC, wyola commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +      <MobileCategorySearch />
sure, you are right

2023-05-30 16:41 UTC, zuzannapaw approved these changes
Only few small things from me. It looks and works great! 🚀

2023-05-30 16:41 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/MobileCategorySearch.tsx
> +import { CategoryFilter } from "components";
I suggest to change order of imports, first external ,after that internal ✔️

2023-05-30 16:41 UTC, zuzannapaw commented on packages/ui/Accordion/Accordion.styles.tsx
> +  font-family: unset;
Do we need `font-family: unset`? 👀

2023-05-30 16:41 UTC, zuzannapaw commented on packages/ui/Accordion/index.tsx
> +import React from "react";
I believe we don't need `import React from "react";`

2023-05-30 18:40 UTC, Alessiass commented on packages/ui/Accordion/Accordion.styles.tsx
> +  font-family: unset;
Yes, we need this to set the font to Inter.

2023-05-30 18:40 UTC, Alessiass commented on apps/web/app/(navigation)/budgets/[id]/MobileCategorySearch.tsx
> +import { CategoryFilter } from "components";
Done 🚀

2023-05-30 18:41 UTC, Alessiass commented on packages/ui/Accordion/index.tsx
> +import React from "react";
I switched the import to ReactNode.

2023-05-30 19:36 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/budgets/[id]/MobileCategorySearch.tsx
> +      <StyledButton onClick={() => console.log("Manage modal")}>
@Alessiass please remove the console.log :D.

2023-05-30 19:37 UTC, monika-klokosinska-intive commented on apps/web/components/CategoryFilter/index.tsx
> +    console.log(categoryEntries);
@Alessiass please remember to remove the console.log :D.

2023-05-30 22:41 UTC, Noshi96 commented on packages/ui/Accordion/Accordion.styles.tsx
> +    </AccordionHeader>
I have tried this without the ref and additional props, and it seems to work. What problems have you noticed with not using React.forwardRef?
```tsx
export const AccordionTriggerHeader = ({
  children,
  className,
}: React.HTMLProps<HTMLHeadingElement>) => (
  <AccordionHeader className="AccordionHeader">
    <AccordionTrigger className={`AccordionTrigger ${className}`}>
      {children}
      <Icon icon={"chevron_right"} className={"iconStyles"} />
    </AccordionTrigger>
  </AccordionHeader>
);
```

2023-05-31 18:14 UTC, Noshi96 approved these changes
It works great! I also tested on a mobile device. Good job! 🚀

2023-05-31 19:28 UTC, wlechowicz approved these changes
LGTM overall, one gripe inline

2023-05-31 19:28 UTC, wlechowicz commented on apps/web/app/(navigation)/budgets/[id]/MobileCategorySearch.tsx
> +        ...{t(dict.categories.settings)}
I don't like the `...` at the beginning. It looks odd since it's followed by a capital letter. Maybe it would make sense at the end, like "Manage...", but I don't think it's necessary at all.

2023-05-31 19:29 UTC, wlechowicz commented
One more complaint, actually. IMO "Manage" is too close to the chevron and users on mobile will fat finger the wrong thing.

![obraz](https://github.com/intive/patronage2023-js/assets/24250766/2ddfd550-b930-4c3b-a4bf-2c184d10d142)

2023-05-31 19:40 UTC, bdeluga approved these changes
Nice :rocket:

2023-06-01 08:41 UTC, wyola approved these changes

2023-06-01 15:06 UTC, merged