fix: fix budgets duplication #P23-383
intive/patronage2023-js pull request #131
Opened 2023-06-01 13:52 UTC by zuzannapaw

<h2> Problem solved 🎉  </h2>

- After adding to/removing budgets from favorites, there are no more duplicated budgets in NavList
- Duplicates are being filtered from the array

<h2> What changed 💭  </h2>

- Added superfetch for getting budget's list for proper error handling

2023-06-01 14:15 UTC, bdeluga approved these changes
Nice work  🚀

2023-06-01 15:30 UTC, Alessiass approved these changes
Looks good. Just food for thought. Whenever there is a need to store unique values we can use Sets: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

2023-06-01 16:10 UTC, AzulloCyll commented on apps/web/components/SideNavigationBar/index.tsx
> +  };
![image](https://github.com/intive/patronage2023-js/assets/65503275/d63fcfcf-1372-401f-920e-328a153d5a51)

You can simplify it

2023-06-01 16:26 UTC, monika-klokosinska-intive commented on apps/web/components/SideNavigationBar/index.tsx
> +  };
@Alessiass @AzulloCyll @zuzannapaw  `Set` will compare the object references, not actual id keys of the objects, so it's not a good fit here. We would have to map the array to only ids first and then use `Set`.

```
const removeDuplicates = (fetchedBudgets: BudgetType[]) => {
    return fetchedBudgets.filter(
      (budget, idx) =>
        fetchedBudgets
          .map((object) => object.id.value)
          .indexOf(budget.id.value) === idx
    );
  };
  ```
is another way to simplify it.

2023-06-01 16:41 UTC, AzulloCyll commented on apps/web/components/SideNavigationBar/index.tsx
> +  };
@monika-klokosinska-intive thank you for correcting us.

So `new Set` works on arrays of primitive data types such as number, string, booleans or nulls.
Never on array of arrays or array of objects :)

@zuzannapaw
You can resolve that conversation 😄

2023-06-01 16:49 UTC, wyola approved these changes
LGTM ⭐

2023-06-01 17:57 UTC, monika-klokosinska-intive commented on apps/web/components/SideNavigationBar/index.tsx
> +  };
@AzulloCyll it will work, but by comparing the references (= addresses where the object is stored in the memory) of the objects. You could have two objects that are exactly the same, but have different references - `Set` will consider them to be two completely different instances and keep both of them. 
Usually with objects you want to compare the actual keys and values, not references, so `Set` will be useless for such  usecases. Same deal with arrays of arrays and arrays of other complex types.

But as you mentioned, primitives work as you would expect them to work, so `Set` is excellent for primitives.

@zuzannapaw please simplify the function by removing `uniqueBudgets` from inside `removeDuplicates`.

2023-06-01 19:20 UTC, zuzannapaw commented on apps/web/components/SideNavigationBar/index.tsx
> +  };
@monika-klokosinska-intive I have applied your suggestion, thank you!

2023-06-01 19:23 UTC, Noshi96 approved these changes
LGTM 🎸

2023-06-01 19:56 UTC, monika-klokosinska-intive approved these changes
@zuzannapaw Looks good! Feel free to merge :)

2023-06-02 13:29 UTC, merged

2023-06-05 11:46 UTC, wlechowicz requested changes

2023-06-05 11:46 UTC, wlechowicz commented on apps/web/components/SideNavigationBar/index.tsx
> +    }));
This is a bug that's been sitting here for a while, might as well fix it now. This adds last budget ref to every single budget on the list, instead of the last one.
```suggestion
    return budgets.map(({ icon, name, id, isFavourite }, index, list) => ({
      ComponentToRender: (
        <>
          <IconStyled icon={validate(icon) ? icon : "help"} iconSize={24} />
          <SpanStyled>{name}</SpanStyled>
          <Favourite
            isFav={isFavourite}
            budgetId={id.value}
            activeHref={`/budgets/${id.value}`}
          />
        </>
      ),
      href: `/budgets/${id.value}`,
      id: id.value,
      ref: index === list.length - 1 ? lastBudgetRef : null,
    }));
```

2023-06-05 11:46 UTC, wlechowicz commented on apps/web/components/SideNavigationBar/index.tsx
> +  };
This complexity of this is like O(n^2) which is bad. Here's a whole thread comparing different solutions:
https://stackoverflow.com/a/58429784/11159848
Solutions with spreading maps and sets look fancy, but don't remove any of the complexity, just hide most of it under newer operators.
One of the simplest solutions is a dictionary-based one, where you add the `id`s of the object to a dictionary as you go, and you skip ones that you already added, like this:
https://stackoverflow.com/a/18923480/11159848