feat: init personal card #P23-392
intive/patronage2023-js pull request #133
Opened 2023-06-02 10:48 UTC by mpiwonski

Task: [personal card task](https://tracker.intive.com/jira/browse/PATRO23-392)

2023-06-04 12:55 UTC, monika-klokosinska-intive commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +  z-index: 100;
@mpiwonski won't anything smaller than 100 work? I know this requires extra testing with other z-indexed elements on the page, but the less you escalate the number, the fewer problems we will have in the future maintaining the code base.

2023-06-04 13:52 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/MainMenu.tsx
> +  console.log(data);
@mpiwonski out with the console.log before merging!

2023-06-04 13:57 UTC, monika-klokosinska-intive commented on packages/ui/PersonalCard/index.tsx
> +  const isTablet = useMediaQuery({ query: "(min-width: 768px)" });
@monika-klokosinska-intive this is a not a great idea! Better to get rid of the query check here, render both elements in the fragment and use css to decide which one will be visible on given resolution. 
Solutions like `useMediaQuery` tend to lead to... doubtful code, at least in my experience. Better to fallback on the css functionality.

2023-06-05 08:46 UTC, aniasgit commented
Merge current main, this branch is out of date.

2023-06-05 12:44 UTC, wyola reviewed
Nice addition!

Two things from me:

1. I think that people with unreasonably long names 😢 should be taken somehow under the consideration, especially on mobile screens

<img width="299" alt="image" src="https://github.com/intive/patronage2023-js/assets/80450315/56f99b1e-bb44-48ec-a0bf-0994f0788684">

2. There are different shadow styles on desktop and on mobile

2023-06-05 14:38 UTC, wyola reviewed
Few more things from me

2023-06-05 14:38 UTC, wyola commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +`;
You have a lot of repetitions between `HoverCardContent` and `PopoverContent`, while you could easily simplify it like below. I smuggled there also `flex-direction: column` for the popover, since I think than on mobile the avatar should be on top and rest of the info below it (helps to solve the long name situation that I mentioned before 😅)

You could change padding to be in `px` in both cases, right now it is once `px` and once `em`.

```
/* Content styles */

const CommonContentStyled = css`
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: ${({ theme }) => theme.personalCard.background};
  border: 1px solid ${({ theme }) => theme.card.border};
  box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.5);
  border-radius: 16px;
  overflow: hidden;
  gap: 20px;
  z-index: 100;
`;

export const HoverCardContent = styled(HoverCard.Content)`
  ${CommonContentStyled}
  padding: 0.8em 2em;
`;

export const PopoverContent = styled(Popover.Content)`
  ${CommonContentStyled}
  padding: 10px;
  flex-direction: column;
`;
```

probably some more playing with styling is needed (like different gap etc), what's above is just a general idea

<img width="296" alt="image" src="https://github.com/intive/patronage2023-js/assets/80450315/a2b1efec-4f63-492c-a93a-1b80e1129250">

2023-06-05 14:38 UTC, wyola commented on packages/ui/PersonalCard/index.tsx
> +                    : user.firstName + user.lastName + `@mail.com`}
I know you are waiting for email to be added by backend, but maybe it is better to have here something that is clearly a placeholder, so that it is not forgotten if the BE change does not happen ;-)

2023-06-05 14:38 UTC, wyola commented on packages/ui/Tooltip/index.tsx
> +  // Instead of {text}, there might be a Personal Card component (it will receive user data ofc) taking {text} as a trigger, and once user hovers on it, hover card will be displayed?
I think that there is no point in mixing those two components :) tooltip is something different, if it ends up not used anywhere in the project then we can just remove it (although I think that Paweł S. end up using it in import/export)

2023-06-05 14:57 UTC, monika-klokosinska-intive commented on packages/ui/PersonalCard/index.tsx
> +}
@wyola @mpiwonski firstly, this is a great catch, there is no need for an `any` here, thanks Ola!
I am on the fence where this component should go, but if it needs business logic - related stuff like `BudgetUser`, `web` might be a better place. A true atomic component would accept props like "image" "title" and "text", not a user object that is then further processed. 
Moving this to `web` is fastest and simplest solution we have.

2023-06-06 13:25 UTC, zuzannapaw reviewed
Great addition to the app ☺️ ! Few thing from me.
I also spotted one thing - was it intended to add yellow border on mobile view when the element on focus? 

![image](https://github.com/intive/patronage2023-js/assets/93678778/2dabe3f3-9ce4-4b71-a0e4-b90ce0c1f3f7)

Well done for now! 💪

2023-06-06 13:25 UTC, zuzannapaw commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +  width: 96px;
That's only my point of view, but I'm not sure about avatar's size. Comparing to other elements on page (specially the main ones, that are more exposed), it seems a bit too overwhelming for me.  

![image](https://github.com/intive/patronage2023-js/assets/93678778/7367a8b5-af3d-41a6-9e9e-9c9023805b72)

This is how it would look like with a bit smaller dimensions, like 70px. 

![image](https://github.com/intive/patronage2023-js/assets/93678778/fe2d820a-b572-485f-866d-c8e0f6405531)

I think it look more neat, but please tell me what do you think about it! 👀

2023-06-06 13:25 UTC, zuzannapaw commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +
look out for gaps 👀

2023-06-06 13:25 UTC, zuzannapaw commented on packages/ui/PersonalCard/index.tsx
> +                    : user.firstName + user.lastName + `@mail.com`}
Instead of adding these strings together, you could simply use template string. It would look like:

```javascript
 {user.name ? user.name : `${user.firstName } ${user.lastName}`}
``` 
```javascript
{user.email ? user.email : `${user.firstName} ${user.lastName} ${@mail.com}`}
```

2023-06-06 13:25 UTC, zuzannapaw commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +  z-index: 100;
I think there will be more problems with z-index in this case:
![image](https://github.com/intive/patronage2023-js/assets/93678778/9426dffa-0459-465d-a2b5-d956467db5e0)

2023-06-06 13:25 UTC, zuzannapaw commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +  padding: 0.8em 2em;
I'm not sure if it's better for paddings to be set in `px`, it gives more control when being on different devices

2023-06-06 20:45 UTC, mpiwonski commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +`;
Thanks @wyola for your insights. These are really thoughtful :)

2023-06-06 20:47 UTC, mpiwonski commented on packages/ui/PersonalCard/index.tsx
> +                    : user.firstName + user.lastName + `@mail.com`}
We discussed that during today's call, however we had not come up with a clear answer how to handle that. As for now, it may remain as it is :)

2023-06-06 21:02 UTC, mpiwonski commented on packages/ui/PersonalCard/index.tsx
> +}
Thanks for the points you have raised. I do agree with you, @monika-klokosinska-intive, that it should receive props and there should not be any special operations to decide what to render inside, although keep in mind there's data discrepancy related to the same data (logically) like image and avatar; name -> firstName and lastName...

2023-06-06 21:45 UTC, mpiwonski commented
> Great addition to the app ☺️ ! Few things from me.
> 
> I also spotted one thing - was it intended to add yellow border on mobile view when the element on focus?
> 
> ![image](https://user-images.githubusercontent.com/93678778/243708862-2dabe3f3-9ce4-4b71-a0e4-b90ce0c1f3f7.png)
> 
> Well done for now! 💪

I guess it's a built-in feature provided by radix for this component :P

2023-06-06 21:49 UTC, mpiwonski commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +  width: 96px;
You may be actually right :) I've changed it to 80px :)

2023-06-07 11:02 UTC, aniasgit commented on packages/ui/PersonalCard/index.tsx
> +        <UserEmail>{email ? email : `${name}@mail.com`}</UserEmail>
If you change email property for optional, you can only display email if it exists

```suggestion
        {email && <UserEmail>{email}</UserEmail>}
```

2023-06-07 11:08 UTC, monika-klokosinska-intive commented on packages/ui/PersonalCard/index.tsx
> +        <UserEmail>{email ? email : `${name}@mail.com`}</UserEmail>
@mpiwonski this is what I would go for as well.

2023-06-07 17:35 UTC, mpiwonski commented on packages/ui/PersonalCard/index.tsx
> +        <UserEmail>{email ? email : `${name}@mail.com`}</UserEmail>
Thanks, I have incorporated that change :)

2023-06-08 09:06 UTC, zuzannapaw approved these changes
Works great! Nice job! 🚀

2023-06-08 09:19 UTC, Alessiass approved these changes
I found small bug -> When you turn on popover on mobile and screen size changes it remains in top left corner. Besides of that it work's fine.
![image](https://github.com/intive/patronage2023-js/assets/94013800/98cdd8bb-2f22-4c34-9d54-7781c992938a)

2023-06-08 12:05 UTC, monika-klokosinska-intive commented on packages/ui/package.json
> +    "react-responsive": "^9.0.2",
@mpiwonski you can remove it from package.json if it's not needed anymore :)

2023-06-08 12:07 UTC, monika-klokosinska-intive approved these changes
@mpiwonski I am giving a tentative approval here to speed things up, but please:
- resolve conflicts with main branch
- remove the unused library  
- @zuzannapaw makes a good point about using `px` , please change the `em` to `px`

2023-06-08 13:06 UTC, wyola requested changes
Two things from me:

- something changed here and avatars are overflowing the container on mobile. It is not like it on main, so it is matter of this branch (this is why I am requesting changes)

![image](https://github.com/intive/patronage2023-js/assets/80450315/ce51ee69-6e75-4668-af48-a0ff72d86c49)

<img width="197" alt="image" src="https://github.com/intive/patronage2023-js/assets/80450315/4d88a4be-4980-45d9-a82d-25653606b5e6">

- when you hover on the grey circle where more users are hiding, and then you display personal card of the first user, you can move to the second one. Idk if there is a quick fix for this the way it is designed now. Probably both Hover Card and Popover have some prop like `side` where you can pass on which side it should display. In this case I would display it on the left, but then on mobile it should be on the right... idk


https://github.com/intive/patronage2023-js/assets/80450315/2c03f874-5c75-40c2-a46e-c11ad5545960

2023-06-08 13:54 UTC, wyola commented
> I found small bug -> When you turn on popover on mobile and screen size changes it remains in top left corner. Besides of that it work's fine. ![image](https://user-images.githubusercontent.com/94013800/244335329-98cdd8bb-2f22-4c34-9d54-7781c992938a.png)

@mpiwonski I've had similar problem with `DropdownMenu` https://github.com/intive/patronage2023-js/pull/119#pullrequestreview-1449199360

check this fix - https://github.com/intive/patronage2023-js/pull/119/commits/617b71b9d43199bba26ee1b27a0a747462601bee

2023-06-08 22:37 UTC, mpiwonski commented on apps/web/app/(navigation)/MainMenu.tsx
> +                  <AvatarStyled src={data.user.image} outlined />
Thanks for your suggestions. I have included them. Please mark this conversation as resolved.

2023-06-09 02:35 UTC, Noshi96 approved these changes
I missed the function of viewing people assigned to a budget on a smartphone, and now thanks to your popover this is possible. I like how it works and looks. 🚀 
I have a few minor suggestions, especially in edge cases such as long usernames and emails

2023-06-09 02:35 UTC, Noshi96 commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
When we have a long username and email address:
![image](https://github.com/intive/patronage2023-js/assets/38572172/8c656650-055c-4383-80ec-ef9b2ebe1636)

https://github.com/intive/patronage2023-js/blob/eb02a9e117d38272c4af80cb74bc88b43935e720/packages/ui/Tooltip/index.tsx#L13-L22
change to `z-index: 5;`

2023-06-09 02:35 UTC, Noshi96 commented on packages/ui/PersonalCard/PersonalCard.styles.tsx
> +`;
```suggestion
export const PopoverContent = styled(Popover.Content)`
  ${CommonContentStyled}
  flex-direction: column;
  max-width: 100vw;

  ${device.tablet} {
    display: none;
  }
`;
```
My suggestion:
![image](https://github.com/intive/patronage2023-js/assets/38572172/a5a6adba-91d5-471e-87b1-c69f96737c6e)

Old one:
![image](https://github.com/intive/patronage2023-js/assets/38572172/b00bffc2-2be3-4c24-b5b3-e3185df92897)

https://github.com/intive/patronage2023-js/blob/2056f416fa542f8d4f16ea4c88701ed951263da5/apps/web/app/(navigation)/budgets/%5Bid%5D/BudgetBasinInformation/PeopleInBudget.tsx#L72

You can change to "top"

https://github.com/intive/patronage2023-js/blob/2056f416fa542f8d4f16ea4c88701ed951263da5/apps/web/components/HiddenUsers/index.tsx#L58

change to "bottom"

2023-06-09 07:43 UTC, wyola approved these changes

2023-06-09 08:56 UTC, aniasgit approved these changes
Looks ands works good 👍

2023-06-09 09:14 UTC, merged