feat: assets #P23-116
intive/patronage2023-js pull request #16
Opened 2023-03-23 14:01 UTC by bdeluga

The best way to test this would be to just throw some images into web/public and test it in Storybook. I added pseudo avatar component as a POC so you can also play around with it.  👋

PS. I also removed public folder from storybook and move it to web - someone was probably using it. SORRY 😨

2023-03-23 17:02 UTC, AzulloCyll approved these changes

2023-03-23 17:50 UTC, Alessiass commented on apps/web/public/avatar.png
G.O.A.T.

2023-03-23 17:52 UTC, Alessiass requested changes
Works great even in storybook!
After renaming the component from "Prove" we are good to go.

2023-03-23 18:55 UTC, monika-klokosinska-intive commented on packages/ui/poc/index.tsx
> +export const Prove = ({ src, alt, width, height }: Props) => {
@bdeluga since this is an avatar, it would be better to accept the `username` string here...

2023-03-23 18:59 UTC, monika-klokosinska-intive commented on apps/storybook/stories/POC.stories.tsx
> +  alt: "alt",
@bdeluga Please use something like `John` or `user123` here (assuming the switch from `alt` to `username` happens, see my comments below), so it gives other developers a better idea how accessibility will be handled :).

2023-03-23 20:18 UTC, bdeluga commented on packages/ui/poc/index.tsx
> +      <Image src={src} alt={alt || ""} fill sizes="100%" />
Since it's POC i just created component as fast as i could just to see if changes works. Wouldn't code something like that haha. This was just to display image from web's public folder, but thanks for good practises 😄

2023-03-23 21:07 UTC, wyola commented on packages/ui/poc/index.tsx
> +      <Image src={src} alt={alt || ""} fill sizes="100%" />
@monika-klokosinska-intive avatar component is a separate task that I was working on (I just opened PR for it). If I understand correctly what @bdeluga is just a way to show that images work, right Bartek?

2023-03-23 21:20 UTC, wyola approved these changes
looks good to me 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/80450315/227365127-cbcb22ff-bc63-4d42-b8a2-bb6fbe38a05c.png">

2023-03-23 22:20 UTC, bdeluga commented on packages/ui/poc/index.tsx
> +      <Image src={src} alt={alt || ""} fill sizes="100%" />
yup 🥇

2023-03-24 16:34 UTC, Alessiass approved these changes

2023-03-26 15:33 UTC, merged