feat: avatar component #P23-111
intive/patronage2023-js pull request #17
Opened 2023-03-23 21:02 UTC by wyola

2023-03-24 16:28 UTC, wlechowicz requested changes

2023-03-24 16:28 UTC, wlechowicz commented on packages/ui/Avatar/index.tsx
> +export const Avatar = ({ username, src, className }: AvatarProps) => {
```suggestion
export const Avatar = ({ username = 'user', src, className }: AvatarProps) => {
```

2023-03-24 16:28 UTC, wlechowicz commented on apps/storybook/stories/Avatar.stories.tsx
> +  margin-right: 16px;
Positioning of the Avatar elements (grid in user profile, collapsed in table) is the responsibility of the parent, not the Avatar itself. So this spacing between Avatar and name should be done with the parent's flex props, like gap.

2023-03-24 16:28 UTC, wlechowicz commented on apps/storybook/stories/Avatar.stories.tsx
> +  height: 120,
This needs to be disabled as a control in the story, because it will show up in storybook as a prop of the Avatar, but it's not - it will confuse others.

2023-03-27 22:02 UTC, Noshi96 commented on packages/ui/Avatar/index.tsx
> +};
You can add ```& React.HTMLProps<HTMLImageElement>``` and skip the type declaration for ```src``` and ```className```

2023-03-28 16:59 UTC, monika-klokosinska-intive commented on packages/ui/Avatar/index.tsx
> +  src: string;
@wyola I believe we also discussed adding `alt` as a prop (for the screen with all avatars where the user selects one). The logic on the image would be along the lines of `alt={alt ? alt : ${username}'s avatar}` then.

2023-03-29 09:41 UTC, wyola commented on packages/ui/Avatar/index.tsx
> +  src: string;
@monika-klokosinska-intive done

2023-03-29 09:42 UTC, wyola commented on packages/ui/Avatar/index.tsx
> +export const Avatar = ({ username, src, className }: AvatarProps) => {
@wlechowicz done

2023-03-29 09:43 UTC, wyola commented on apps/storybook/stories/Avatar.stories.tsx
> +  height: 120,
@wlechowicz it was removed at all after changes we discussed on slack

2023-03-29 10:09 UTC, aniasgit approved these changes
Looks good to me 👍

2023-03-29 10:44 UTC, zuzannapaw approved these changes

2023-03-29 11:03 UTC, mpiwonski approved these changes

2023-03-29 11:03 UTC, mpiwonski commented on apps/storybook/stories/Avatar.stories.tsx
> +  > * + * {
Nicely done here! 👍

2023-03-29 12:32 UTC, wlechowicz commented on packages/ui/Avatar/index.tsx
> +};
Contrary to things like button or link, we don't want the Avatar to accept all the properties of img, such as width and height, and we have no intention of passing them down to the img element. Therefore it's fine to declare our own prop types without extending image element.

2023-03-29 12:35 UTC, wlechowicz requested changes
Looks good overall, one minor change requested.

2023-03-29 12:49 UTC, monika-klokosinska-intive commented on apps/storybook/stories/Avatar.stories.tsx
> +`;
@wyola new line please!

2023-03-29 13:18 UTC, wyola commented on packages/ui/Avatar/index.tsx
> +  hasOutline?: boolean;
@wlechowicz done

2023-03-29 13:19 UTC, wyola commented on apps/storybook/stories/Avatar.stories.tsx
> +`;
@monika-klokosinska-intive done

2023-03-29 13:23 UTC, monika-klokosinska-intive approved these changes

2023-03-29 15:08 UTC, wlechowicz approved these changes

2023-03-29 15:12 UTC, merged