feat: sign-in page layout #P23-150
intive/patronage2023-js pull request #18
Opened 2023-03-26 11:33 UTC by AzulloCyll

Added simple global css reset file to get rid of unneccesary margin on <body> and set box-sizing: border-box; on all elements.

Go to `http://localhost:3000/sign-in` to see result of my work.

2023-03-27 18:26 UTC, Alessiass requested changes

2023-03-27 18:26 UTC, Alessiass commented on apps/web/app/layout.tsx
> +          {/* <Nav /> */}
The change is good still. The Nav should be completely removed from root layout since it only occurs in certain pages.

2023-03-27 18:26 UTC, Alessiass commented on apps/web/app/sign-in/layout.tsx
The layout location should be changed since it's not only used in sign-in page.

2023-03-27 18:46 UTC, zuzannapaw commented on apps/web/app/sign-in/layout.tsx
> +              <StyledP>Use your email to log in to your team workspace</StyledP>
What do you think of instead of `<StyledP>` use full name of tags like `<StyledParagraph>`? It could help with clarity of component's names. 😊

2023-03-27 18:46 UTC, zuzannapaw commented on apps/web/app/sign-in/layout.tsx
> +  display: block;
I think `h1` has display block by it's nature 🔲🌳 , so you don't need to worry about adding it in styles.

2023-03-28 05:22 UTC, AzulloCyll commented on apps/web/app/layout.tsx
> +          {/* <Nav /> */}
So I've removed Nav completly.

2023-03-28 05:23 UTC, AzulloCyll commented on apps/web/app/sign-in/page.tsx
> +}
Ok. Changed to Ipsum. :D

2023-03-28 05:26 UTC, AzulloCyll commented on apps/web/app/sign-in/layout.tsx
> +              <StyledP>Use your email to log in to your team workspace</StyledP>
Thanks. I've changed it to ParagraphStyled due to other elements naming convention.

2023-03-28 05:26 UTC, AzulloCyll commented on apps/web/app/sign-in/layout.tsx
> +  display: block;
Thats true. Deleted this line.

2023-03-28 06:48 UTC, AzulloCyll commented on apps/web/app/sign-in/layout.tsx
Moved my layout to auth folder, it can serve sign-in and sign-up.
I'm still thinking about that solution.

2023-03-28 11:57 UTC, aniasgit commented on apps/web/app/auth/sign-in/layout.tsx
> +        <StyledH1>Log in with your email</StyledH1>
I think that because of naming convention H1Styled would be better.

2023-03-28 12:12 UTC, aniasgit commented on apps/web/app/auth/sign-in/page.tsx
> +      <p style={{ margin: "50px" }}>
Instead of margin here, you can use padding in Card component

2023-03-28 15:44 UTC, AzulloCyll commented on apps/web/app/auth/sign-in/layout.tsx
> +        <StyledH1>Log in with your email</StyledH1>
Right. Thanks

2023-03-28 15:47 UTC, AzulloCyll commented on apps/web/app/auth/sign-in/layout.tsx
> +
Thanks, it works good.

2023-03-29 06:15 UTC, AzulloCyll commented on apps/web/lib/css-variables.tsx
> +};
added new line

2023-03-29 12:54 UTC, monika-klokosinska-intive approved these changes

2023-03-29 15:13 UTC, wlechowicz approved these changes

2023-03-29 15:41 UTC, wlechowicz requested changes
Actually, one change to be made.
The layout that you put in `app/(regflow)/sign-in/layout.tsx` will be the common layout for both sign in and sign up, so it should all be the de facto regflow layout located in `app/(regflow)/layout.tsx` as every page under (regflow) group will use this layout, not just the sign-in page.

2023-03-29 18:47 UTC, aniasgit approved these changes
Looks good 👍

2023-03-30 10:30 UTC, wlechowicz approved these changes
This will be refactored as a follow up - layout needs to be made server side, so all the styled components need to be moved out of the layout iself.
We will also explore better solutions rather than usePathname for the left column content.

2023-03-30 10:48 UTC, merged