hotfix: buttongroup-render method #P23 121
intive/patronage2023-js pull request #19
Opened 2023-03-27 14:31 UTC by bdeluga

Had to use `import {Fragment} from 'react'` to apply key, because apparently browser was smoking red, when using my component.
Also used `Icon` in story instead of `<span>` for icon.

2023-03-27 15:01 UTC, mpiwonski requested changes

2023-03-27 15:26 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
> +          </Fragment>
Fragment was already introduced, in form of `<></>` but this way i couldn't set key, so i imported `Fragment` and used it. 🚀

2023-03-27 15:31 UTC, mpiwonski approved these changes

2023-03-27 17:56 UTC, Alessiass approved these changes
Looks fine, still we need to unify our prettier config because constant reformatting obfuscates code during review.

2023-03-28 11:45 UTC, aniasgit approved these changes

2023-03-28 16:50 UTC, monika-klokosinska-intive approved these changes

2023-03-29 15:25 UTC, wlechowicz requested changes

2023-03-29 15:25 UTC, wlechowicz commented on apps/storybook/stories/ButtonGroup.stories.tsx
> +const FixedWidth: ComponentStory<typeof ButtonGroup> = args => (
You have conflicting formatter settings. This will be fixed in the new config story, for now please use Prettier with those basic settings:
```
{
  "arrowParens": "always",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "singleAttributePerLine": false,
  "bracketSameLine": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "es5",
  "useTabs": false
}

2023-03-29 15:25 UTC, wlechowicz commented on packages/ui/ButtonGroup/index.tsx
> +          <Fragment key={`group-${index}`}>
index-based key is almost always a bad idea. If you change the order, the elements will stay the same but with different keys, so not only everything will re-render, but animations will not work if you try to add something like autoanimate etc.

Also a key on Fragment makes little sense, that's why you were seeing an error in the first place, probably. You should wrap the input and the label in something real (an actual element) and put the key on that.

2023-03-29 15:25 UTC, wlechowicz commented on packages/ui/ButtonGroup/index.tsx
>              <label key={`index-${index}`} htmlFor={`button-${index}`}>
You don't need keys here, only on the parent.

2023-03-29 16:31 UTC, wyola commented on packages/ui/ButtonGroup/index.tsx
>  export const ButtonGroup = ({ options, secondary }: GroupProps) => {
@bdeluga shouldn't this component have some option for a default value? right now nothing is checked at start and those button groups are used on pages like "Bills" where when user lands on it something should be selected so the content renders 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/80450315/228606462-5500debd-23bd-4866-b966-94dfd506b183.png">

2023-03-30 07:28 UTC, monika-klokosinska-intive approved these changes

2023-03-30 10:22 UTC, bdeluga commented on apps/storybook/stories/ButtonGroup.stories.tsx
> +const FixedWidth: ComponentStory<typeof ButtonGroup> = args => (
Done.

2023-03-30 10:22 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
>              <label key={`index-${index}`} htmlFor={`button-${index}`}>
Changed.

2023-03-30 10:24 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
>  export const ButtonGroup = ({ options, secondary }: GroupProps) => {
Added `defaultChecked?: boolean`, thanks !

2023-03-30 10:24 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
> +`;
Done.

2023-03-30 12:28 UTC, monika-klokosinska-intive requested changes

2023-03-30 12:41 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
>              <input
Right! Thanks for pointing it out chief 👀

2023-03-30 12:48 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
> +          <Fragment key={`group-${index}`}>
Problem was that Fragment is being rendered in `Array.map` and it needs key, even though it does not appear in DOM tree... I was using Fragment to avoid going deeper in css selector, it works fine imo.

About index-based key, i strongly agree, one solution could be requirement of id in single option object, what do you think about it ? 👀 @wlechowicz

2023-03-30 13:16 UTC, bdeluga commented on packages/ui/ButtonGroup/index.tsx
> +          <Fragment key={`group-${index}`}>
Right! 🚀

2023-03-30 13:53 UTC, bdeluga commented
@monika-klokosinska-intive , @wlechowicz 
Did i resolved your requests ?

2023-03-30 18:51 UTC, wlechowicz commented on packages/ui/ButtonGroup/index.tsx
> +          <Fragment key={`group-${index}`}>
Yeah, that sounds ok

2023-03-30 18:55 UTC, wlechowicz requested changes
Some typos to fix, rest looks good.

2023-03-30 18:55 UTC, wlechowicz commented on apps/storybook/stories/ButtonGroup.stories.tsx
> +      id: "expanses",
```suggestion
      id: "expenses",
```

2023-03-30 18:55 UTC, wlechowicz commented on apps/storybook/stories/ButtonGroup.stories.tsx
> +      id: "expanses",
```suggestion
      id: "expenses",
```

2023-03-30 19:09 UTC, wlechowicz approved these changes

2023-03-30 19:11 UTC, merged