feat: atomic component - datepicker #P23-214
intive/patronage2023-js pull request #37
Opened 2023-04-10 10:06 UTC by AzulloCyll

## Getting Started

Component is using third party library called [react-datepicker](https://www.npmjs.com/package/react-datepicker) so please run following commands to install needed packages.

```bash
npm install react-datepicker --save
```

```bash
npm install "@types/react-datepicker"
```

You can look at it in our storybook, or on demo page at route `/datepicker`

## Localization

Component is localized in two languages at now: English wich is default, and Polish. Language can be set using `lang="pl"` prop.

If you want to add more languages you need to import specific language locale from `date-fns/locale/...` like in example below

```bash
import es from 'date-fns/locale/es'
```

and register it in components useState switch function.

## Known Issues

When using year dropdown it shows warning about [findDOMNode](https://stackoverflow.com/questions/71989683/finddomnode-is-deprecated-in-strictmode-using-react-datepicker-with-react-hook)

You can simply ignore it in console by right clicking that warning and choosing "Hide messages from react_devtools_backend.js". Of course this warning will not be visible in production version of our application.

Second issue is that we can't change years with keyboard.

## Usefull links

Demo:
[react-datepicker](https://reactdatepicker.com/)

2023-04-10 15:18 UTC, Noshi96 commented on packages/ui/DatePicker/index.tsx
> +        break;
I think it should not be here. It should be in LanguageContext.tsx. DatePicker will only get locale/lang as props and set it in the <DatePicker>

2023-04-10 17:34 UTC, Noshi96 commented on packages/ui/DatePicker/index.tsx
> +        break;
I think you don't need either useState or switch. You can replace the switch with an object:
```javascript
type DatePickerLanguageConfigType = {
  [key: string]: Locale;
};

const datePickerLanguageConfig: DatePickerLanguageConfigType = {
  en: en,
  pl: pl,
  default: en,
};
```

2023-04-10 18:57 UTC, Noshi96 commented
Good job on customizing the styles for the calendar. I like how it looks, also nice description of the PR :D

2023-04-10 19:05 UTC, Noshi96 commented on packages/ui/DatePicker/index.tsx
There is one problem with accessibility. Your year picker is actually wrapped in a div, making it inaccessible within the use of tabs and spaces. 

![image](https://user-images.githubusercontent.com/38572172/230974323-58ac770d-71ef-43b5-8f8e-d781c2c4457b.png)

2023-04-11 07:08 UTC, bdeluga commented
@AzulloCyll Please resolve conflicts ! 👀 Except that the date picker looks very nice.  🚀

2023-04-11 19:46 UTC, monika-klokosinska-intive approved these changes

2023-04-11 19:47 UTC, monika-klokosinska-intive requested changes
@AzulloCyll the deployments are failing - please take a look before merging!

2023-04-11 20:30 UTC, AzulloCyll commented
@monika-klokosinska-intive But on my computer it's building correctly I don'k know why it's not building.

2023-04-12 07:14 UTC, monika-klokosinska-intive approved these changes

2023-04-12 09:23 UTC, wyola approved these changes
Looks good to me!

2023-04-12 09:29 UTC, zuzannapaw approved these changes

2023-04-12 10:01 UTC, merged