feat: modal component #P23-216
intive/patronage2023-js pull request #38
Opened 2023-04-11 14:11 UTC by aniasgit

2023-04-11 16:56 UTC, AzulloCyll approved these changes
Looks good! :D

2023-04-11 16:57 UTC, Alessiass requested changes

2023-04-12 09:28 UTC, aniasgit commented on packages/ui/Modal/index.tsx
> +    <ModalStyled onClick={onClose}>
fixed

2023-04-12 09:52 UTC, monika-klokosinska-intive approved these changes

2023-04-12 16:21 UTC, Alessiass approved these changes

2023-04-12 16:50 UTC, merged