feat: password page component #P23-208
intive/patronage2023-js pull request #39
Opened 2023-04-11 14:33 UTC by Alessiass

Component displaying password validation form, requires two props to render:

- onNext: Function called when "Continue" button is pressed. Takes validated password as an argument - plain string.
- onBack: Function called when "Back" button is pressed.

Example of usage:
`    <PasswordSubComponent
      onNext={(text) => console.log(text)}
      onBack={() => console.log("Back")}
    />`

Component can be checked on 
`/sign-up/playground`

2023-04-11 20:37 UTC, Noshi96 requested changes

2023-04-11 20:37 UTC, Noshi96 commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +                      /[!"#$%&'()+,-./:;<=>?@[\]^_`{|}~]/,
You missed the "*" as a special character

2023-04-11 20:37 UTC, Noshi96 commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +  @media ${device.mobile} {
device.mobile no longer exists, do marge/rebase with main

2023-04-11 21:11 UTC, bdeluga commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +}: PasswordSubComponentProps) => {
Please consider adding `password:string` that is being passed by controller so when user navigates his password persist. 👀

2023-04-12 13:56 UTC, aniasgit commented on packages/ui/theme.tsx
> +    header: colors.Teal10,
I think we can use primary for headers as well.

2023-04-12 16:44 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +`;
Totally agree. Fixed.

2023-04-12 16:45 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +  font-size: 14px;
Good point. Fixed :D.

2023-04-12 16:45 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +  flex-wrap: nowrap;
Done

2023-04-12 16:45 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +                      /[!"#$%&'()+,-./:;<=>?@[\]^_`{|}~]/,
Added

2023-04-12 16:45 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +                        />
Didn't noticed that before. I've copied the name from field to inputs. Great find!

2023-04-12 16:46 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +  @media ${device.mobile} {
Removed - I just used it to check how it will look and behave on mobile.

2023-04-12 16:47 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/PasswordSubComponent.tsx
> +}: PasswordSubComponentProps) => {
Done :D

2023-04-12 16:47 UTC, Alessiass commented on packages/ui/theme.tsx
> +    header: colors.Teal10,
Good point. I removed the text completely and just left primary and secondary.

2023-04-12 18:09 UTC, monika-klokosinska-intive commented
@Alessiass one problem I spotted:
- card doesn't fit the screen < 450px. Please either fix or discuss with @bdeluga and other members of the team how to handle it once the PR merged so we have a plan for it
![Zrzut ekranu z 2023-04-12 o 20 05 11](https://user-images.githubusercontent.com/46372708/231546325-d6ee8e63-50da-4d37-9bea-bf79ce872f60.png)

If that's handled, we are good to go IMHO.

2023-04-12 18:37 UTC, bdeluga requested changes
Left some comments, let's resolve them and marge it to main because component is really nice ! 🚀

2023-04-12 18:37 UTC, bdeluga commented on packages/ui/Separator/index.tsx
> +  margin: 0;
Global.css makes every element `margin:0` by default so i think its unnecessary.

2023-04-12 18:37 UTC, bdeluga commented on packages/ui/Separator/index.tsx
> +  z-index: 1;
What's the logic behind it, I've checked `<Separator label="tekst"/>` with and without this line of code, and it behaved same way. 😕

2023-04-12 19:05 UTC, bdeluga commented
> @Alessiass one problem I spotted:
> 
> * card doesn't fit the screen < 450px. Please either fix or discuss with @bdeluga and other members of the team how to handle it once the PR merged so we have a plan for it
>   ![Zrzut ekranu z 2023-04-12 o 20 05 11](https://user-images.githubusercontent.com/46372708/231546325-d6ee8e63-50da-4d37-9bea-bf79ce872f60.png)
> 
> If that's handled, we are good to go IMHO.

It looks like mobile view is missing. 📱

2023-04-12 19:35 UTC, Alessiass commented on packages/ui/Separator/index.tsx
> +  z-index: 1;
There were some problems with Separator component visibility and we overengineered the solution a bit :D.

2023-04-12 19:43 UTC, Alessiass commented
@monika-klokosinska-intive, @bdeluga - component is wrapped in FormWrapper which has fixed dimensions but the component itself is responsive. I've added media query to show it on preview.
I assumed that FlowController will have main container for all 4 components to keep them in place and this part should be refactored later on.

2023-04-12 19:50 UTC, monika-klokosinska-intive approved these changes

2023-04-12 20:09 UTC, bdeluga approved these changes
APPROVED ! 🚀 
![image](https://user-images.githubusercontent.com/79754698/231573149-d6a70d65-3e5a-4621-999e-408490cf6f0a.png)

Classy. 🍷

2023-04-12 20:47 UTC, Noshi96 approved these changes

2023-04-12 21:02 UTC, merged