feat: profile screen component #P23-209
intive/patronage2023-js pull request #40
Opened 2023-04-11 16:00 UTC by PawelPazderski

## Component for Sign Up Flow Controller - Step 3/4
### Avatar selection and name form for First name and Last name
ticket: https://tracker.intive.com/jira/browse/PATRO23-209

The component will need two props for future actions - `back() ` (go back one step) and `done()` where the values from the form and selected Avatar will be passed

### Changes
- introduces a number of changes to Avatar Selector appearance (eg. wrapper, mobile before and after avatar list shading elements)
- adding necessary fields to theme and dictionary files

*Due to onSubmitValidate operation problems inputs validation is being done with onChangeValidate*

2023-04-11 16:33 UTC, wyola commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +            <SeparatorLine />
There is a `Separator` component (its styles were updated in `PasswordScreen` since it displayed well in the storybook but not otherwise - the update is not yet merged to `main`)

2023-04-11 16:36 UTC, wyola commented on apps/web/lib/dictionary.tsx
> +    step3: {
I would name it rather "profileScreen" or similar - in case the order of steps changes or there are more steps. The name in the dictionary should be more general.

2023-04-11 16:39 UTC, PawelPazderski commented on apps/web/lib/dictionary.tsx
> +    step3: {
Yep you're right, I renamed the component during the process but didn't change that in dict, thanks!

2023-04-11 16:41 UTC, PawelPazderski commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +            <SeparatorLine />
I added that for now I tried to use the Separator component though but didn't see anything somehow did't want to loose time on that I'll get back to it probably some detail to fix.

2023-04-11 16:42 UTC, wyola commented on packages/ui/Input/index.tsx
> +  onSubmit,
why do you add it here?

2023-04-11 16:46 UTC, wyola commented on apps/web/lib/dictionary.tsx
> +        }
It is repeated both for first and last name - maybe it is better to move it one level up and name it "inputError"?

2023-04-11 16:47 UTC, wyola commented on apps/web/lib/dictionary.tsx
> +        en: "Create my account",
on design it is "Create account"

2023-04-11 16:49 UTC, AzulloCyll commented
![image](https://user-images.githubusercontent.com/65503275/231232856-a59ac672-3cd3-4db7-90ca-752a74bca30d.png)

Strange behavior. Maybe it need to switch display mode on other breakpoint. 
Overall component looks very good! :D Good job!

2023-04-11 16:51 UTC, PawelPazderski commented
> ![image](https://user-images.githubusercontent.com/65503275/231232856-a59ac672-3cd3-4db7-90ca-752a74bca30d.png)
> 
> Strange behavior. Maybe it need to switch display mode on other breakpoint. Overall component looks very good! :D Good job!

I did't have that on my side - strange - must check what the problem is then, thanks!

2023-04-11 16:52 UTC, wyola commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +            <SeparatorLine />
sure, we fixed it with Bartek K., you can see it on his branch later 🤗

2023-04-11 21:16 UTC, bdeluga commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +export const ProfileScreen = ({ back, done }: ProfileScreenProps) => {
Please consider also adding `profileInfo: {
    name: string;
    surname: string;
    avatar: string;
}` which will be passed from controller so user data persist in case of validation error e.g email taken.❌

2023-04-11 22:19 UTC, Noshi96 commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +`;
You can remove this wrapper and add gap:16px; in ButtonsWrapper. Same behavior less divs.

2023-04-12 10:01 UTC, monika-klokosinska-intive commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +export const ProfileScreen = ({ back, done }: ProfileScreenProps) => {
@PawelPazderski @bdeluga is right, we need to pass the data from the user back to the parent component - so the parent component has access to them as well

2023-04-12 12:41 UTC, PawelPazderski commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +export const ProfileScreen = ({ back, done }: ProfileScreenProps) => {
Of course, wasn't sure at the moment of creating PR about the structure of the data for the Controller, I'll do as @bdeluga suggests then, as one object. Thanks

2023-04-12 12:59 UTC, PawelPazderski commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +`;
Good idea, thanks

2023-04-12 14:39 UTC, aniasgit commented on packages/ui/AvatarSelector/index.tsx
> +  width: 360px;
In the smallest screen (375px) this avatar selector is a bit too big. For the screen to look like in Figma, it should be 343px

2023-04-12 14:42 UTC, aniasgit commented on packages/ui/theme.tsx
> +export const colors = {
Do we need export this colors? I don't see any place where you import them.

2023-04-12 16:10 UTC, PawelPazderski commented on packages/ui/theme.tsx
> +export const colors = {
it's no use here you're right

2023-04-12 16:16 UTC, PawelPazderski commented on packages/ui/AvatarSelector/index.tsx
> +  width: 360px;
I would leave as much as we can here 348 px still fits good in the smallest width

2023-04-12 19:22 UTC, Alessiass commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +                  onInputCleared={() => setValue("")}
```suggestion
                  onChange={(e) => setValue(e.currentTarget.value)}
                  onBlur={onBlur}
```
Clearing value also applies as a change. Is onInputCleared necessary?

2023-04-12 19:27 UTC, bdeluga commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +} & React.HTMLProps<HTMLDivElement>;
```suggestion 
type ProfileScreenProps = {
  back: () => void;
  done: ( profileInfo: {firstName: string; lastName: string; avatar: string} ) => void;
  profileData: {firstName:string,lastName:string,avatar:string};
} & React.HTMLProps<HTMLDivElement>;

2023-04-12 19:31 UTC, bdeluga requested changes
Resolve suggestion, other than that, component works as expected ! 🚀

2023-04-12 19:36 UTC, PawelPazderski commented on apps/web/app/(regflow)/sign-up/ProfileScreen.tsx
> +                  onInputCleared={() => setValue("")}
It's a input clearing option, it is provided by the input - is it neccessary? hard to tell

2023-04-12 19:52 UTC, monika-klokosinska-intive commented
@PawelPazderski please resolve conflicts!

2023-04-12 20:06 UTC, bdeluga approved these changes
Good job, also thanks for repairing AvatarSelector 🙌, approved. 🚀

2023-04-12 20:20 UTC, Alessiass approved these changes
Works like a charm

2023-04-12 20:28 UTC, monika-klokosinska-intive approved these changes

2023-04-12 20:29 UTC, merged