refinement: P23-236-side-navbar-submenu
intive/patronage2023-js pull request #46
Opened 2023-04-17 00:01 UTC by mpiwonski

That is refinement of side navigation bar sub menu component (https://tracker.intive.com/jira/browse/PATRO23-236).

2023-04-17 08:40 UTC, zuzannapaw reviewed
Component looks and works great. Although I would still work on SideNavBar placement to make it look like on design (there is still a gap on the right side when sidebar is closed). What do you also think about create dummy pages for users (when I click on some user in Teams, error 404 occurs)? Speaking of dummy pages, when I click on pages in Settings, the page name does not change in main card (it's always "Settings"). Also please check  `/budgets/[id]/page.tsx` and `budgets/page.tsx` and please delete unused imports. Well done for this component 🚀

2023-04-17 11:35 UTC, mpiwonski commented
> Component looks and works great. Although I would still work on SideNavBar placement to make it look like on design (there is still a gap on the right side when sidebar is closed). What do you also think about create dummy pages for users (when I click on some user in Teams, error 404 occurs)? Speaking of dummy pages, when I click on pages in Settings, the page name does not change in main card (it's always "Settings"). Also please check `/budgets/[id]/page.tsx` and `budgets/page.tsx` and please delete unused imports. Well done for this component 🚀

Thanks for your comments. Side navigation bar placement has been fixed and now it looks like it is shown in design. There won't be "Team" submenu as it has just been confirmed by clients (99%) - I was allowed to remove that item. As far as settings subpage is concerned, it has been designed to catch all possible instances of settings and as a result user is being redirected to one settings page as of now. As for budgets, that should be commented by @wlechowicz :)

2023-04-17 15:40 UTC, Noshi96 reviewed
1. Opening a submenu expands the remaining content. We need to deal with this or consider overlapping submenus with the main card. 

![image](https://user-images.githubusercontent.com/38572172/232531802-2123b53e-ffff-485c-bc34-af2e2b9e4d0f.png)

2. The list of the main menu is a little too close to the left edge, and to the sub menu (design screen)

![image](https://user-images.githubusercontent.com/38572172/232532447-1970efe1-5645-4d20-8fe2-73aedecc06da.png)

2023-04-17 15:40 UTC, Noshi96 commented on packages/ui/SideNavigationBar/SubMenu/index.tsx
You can place style declarations above component declarations

2023-04-17 16:37 UTC, zuzannapaw approved these changes
Nicely applied changes. Sidenav placement looks much better 👍  Just a few little details from me, besides that, I think the component is overall fine

2023-04-17 16:37 UTC, zuzannapaw commented on packages/ui/Input/SearchInput/index.tsx
> +      <StyledIconSerch>
a little typo here in "StyledIconSerch" :)

2023-04-17 16:37 UTC, zuzannapaw commented on packages/ui/SideNavigationBar/SubMenu/index.tsx
I agree with this comment:)

2023-04-17 16:37 UTC, zuzannapaw commented on packages/ui/Input/SearchInput/index.tsx
> +import React, { useContext, useRef } from "react";
I'm not sure if we still need `import React from "react"` 👀

2023-04-17 19:50 UTC, monika-klokosinska-intive commented on packages/ui/Input/SearchInput/index.tsx
> +import React, { useContext, useRef } from "react";
@zuzannapaw @mpiwonski the ui package should work fine without importing `React` - please give it a try!

2023-04-18 05:29 UTC, AzulloCyll commented on packages/ui/Input/SearchInput/index.tsx
> +import React, { useContext, useRef } from "react";
@mpiwonski I think that SearchInput shouldn't be nested in Input folder. SearchInput should go to `ui` directory

2023-04-18 06:14 UTC, bdeluga approved these changes
Minor tweaks, overall nice refinement 🥇

2023-04-18 06:14 UTC, bdeluga commented on packages/ui/NavList/index.tsx
> +  padding: 0;
No need for extra padding, its already declared in global.css 👀 

![image](https://user-images.githubusercontent.com/79754698/232685205-d116bb24-9399-442a-a5ee-317586c61e84.png)

2023-04-18 14:05 UTC, wlechowicz requested changes
The big change that needs to happen, is that the design shows 2 different behaviors of the side nav submenu - one where it pushes the content aside, squishing it, and the other, where it overlays the content.
We have to choose one behavior, and since we wouldn't be able to squish content - such as budget details - in a way that makes sense, we should choose to make the submenu show on top of the content, rather than squishing it to the side.

2023-04-19 12:06 UTC, mpiwonski commented on packages/ui/SideNavigationBar/SubMenu/index.tsx
Thanks @Noshi96 and @zuzannapaw for your insights. The changes you have mentioned have been addressed. Please take a look at the latest commit.

2023-04-19 12:07 UTC, mpiwonski commented on packages/ui/Input/SearchInput/index.tsx
> +      <StyledIconSerch>
Kudos @zuzannapaw eagle eye!

2023-04-19 12:07 UTC, mpiwonski commented on packages/ui/Input/SearchInput/index.tsx
> +import React, { useContext, useRef } from "react";
I thought it could lay under Input as it inherits some characteristics from it :)

2023-04-19 12:08 UTC, mpiwonski commented on packages/ui/Input/SearchInput/index.tsx
> +          <Icon icon="cancel" color={theme.input.main} iconSize={20} />
Thanks @bdeluga. Changes have been made accordingly.

2023-04-19 12:08 UTC, mpiwonski commented on packages/ui/NavList/index.tsx
> +  padding: 0;
Yes, indeed, however it was for a purpose of storybook styling, but I deleted that anyway :)

2023-04-19 12:09 UTC, mpiwonski commented
> The big change that needs to happen, is that the design shows 2 different behaviors of the side nav submenu - one where it pushes the content aside, squishing it, and the other, where it overlays the content. We have to choose one behavior, and since we wouldn't be able to squish content - such as budget details - in a way that makes sense, we should choose to make the submenu show on top of the content, rather than squishing it to the side.

Thanks @wlechowicz for your insight. I have made a proper fix. Please take a look at the latest deployment.

2023-04-19 18:42 UTC, monika-klokosinska-intive commented on packages/ui/SideNavigationBar/SideNavigationBarButton/index.tsx
> +  /* padding: 0; */
@mpiwonski if you are not using this css value, delete it altogether instead of just commenting.
Leaving comments like this in code will eventually lead to bloat and mess (and you can always check previous history through git, so it's not like you are losing anything by deleting).

2023-04-19 18:44 UTC, monika-klokosinska-intive commented on packages/ui/SideNavigationBar/SubMenu/index.tsx
> +
@mpiwonski is there any reason for the new lines here? If not, delete them - a new line here and there contributes to the amount one has to scroll to get to the part of the code they are looking for.

2023-04-20 07:12 UTC, mpiwonski commented on packages/ui/SideNavigationBar/SubMenu/index.tsx
> +
The sole reason was to separate common parts of CSS :)

2023-04-20 11:50 UTC, wlechowicz requested changes
There's a bug - when I click Budgets, then, say, Bills, the menu disappears, which is OK. But when I click Budgets then, nothing happens. I have to click Budgets second time for it to kick in. I think it's interfering with your logic for closing the menu when the active item is clicked in the sidebar (not in the submenu).

2023-04-20 21:03 UTC, mpiwonski commented
> There's a bug - when I click Budgets, then, say, Bills, the menu disappears, which is OK. But when I click Budgets then, nothing happens. I have to click Budgets second time for it to kick in. I think it's interfering with your logic for closing the menu when the active item is clicked in the sidebar (not in the submenu).

Bug fixed.

2023-04-23 13:34 UTC, AzulloCyll approved these changes

2023-04-23 19:39 UTC, Noshi96 reviewed
It looks very good after all the changes you made!🚀 I have one objection. When we use tab to navigate the navigation bar, when we click the space bar, the submenu opens, but the focus is still in the main navigation bar, so the next tab click does not move to the submenu. The behavior where when you click, the focus is redirected to the submenu can be achieved by placing the ```<SubMenu>``` in the ```<SideNavigationBarButton>``` as ```children```, and adding new conditional rendering from your ```activeFlag```

2023-04-24 18:12 UTC, PawelPazderski approved these changes
Ovarall it looks and works really nice, great job! I would suggest adding an option to close the menu by clicking outside it maybe, apart from that all looks good to me.

2023-04-25 17:40 UTC, wlechowicz approved these changes

2023-04-25 20:17 UTC, merged