feat: currency amount component #P23-248
intive/patronage2023-js pull request #50
Opened 2023-04-20 11:49 UTC by Noshi96

2023-04-20 14:17 UTC, AzulloCyll approved these changes

2023-04-20 16:44 UTC, Alessiass requested changes
There is a difference in data display.

🚀Dev:
![image](https://user-images.githubusercontent.com/94013800/233432914-b8b5f9af-9eb9-484f-877f-61b3ee7ef657.png)

🎨Design:
![image](https://user-images.githubusercontent.com/94013800/233433017-80b474ad-0d18-40e2-a265-6ba80b8fe75a.png)

2023-04-20 17:38 UTC, Noshi96 commented on packages/ui/CurrencyAmount/index.tsx
> +    .replace(/\s+/, " ")
@AzulloCyll "some browsers put a space between the currency and the value resulting in the output that OP wanted. In that case, the formatting above will result in 2 spaces" https://stackoverflow.com/questions/44533919/space-after-symbol-with-js-intl

2023-04-20 17:56 UTC, Noshi96 commented
> There is a difference in data display format.
> 
> 🚀Dev: ![image](https://user-images.githubusercontent.com/94013800/233432914-b8b5f9af-9eb9-484f-877f-61b3ee7ef657.png)
> 
> 🎨Design: ![image](https://user-images.githubusercontent.com/94013800/233433017-80b474ad-0d18-40e2-a265-6ba80b8fe75a.png)

@Alessiass In the meeting, we said that we want to use "Locale" formatting. There will be differences between "en-US", "de-DE", "pl-PL". I think it should not fit into the design.

2023-04-20 18:20 UTC, Alessiass approved these changes

2023-04-20 19:07 UTC, monika-klokosinska-intive approved these changes

2023-04-24 07:01 UTC, bdeluga approved these changes

2023-04-24 10:06 UTC, aniasgit approved these changes

2023-04-24 16:28 UTC, merged