feat: three dots component #P23-249
intive/patronage2023-js pull request #54
Opened 2023-04-23 12:42 UTC by zuzannapaw

**Info:**

- link to task in jira: https://tracker.intive.com/jira/browse/PATRO23-249 👀,
- ThreeDots components based on `DropdownMenu` from radix (https://www.radix-ui.com/docs/primitives/components/dropdown-menu),
- component accepts `items` as prop in order to be more generic - it can be used in diffrent places with diffrent items,
- additional design: background on hover, outline on focus, border-radius of items.

**Main question:**

Does `items` array should be an array of strings, links or buttons? - (key aspect of component's functionality - will it relocate user to another page?) 🤔

2023-04-23 13:19 UTC, AzulloCyll approved these changes
Please correct two little errors, and it's goot to merge.

2023-04-23 13:19 UTC, AzulloCyll commented on packages/ui/ThreeDots/index.tsx
> +          {items.map((item, i) => {
`i` variable is not used in further code.

2023-04-23 13:19 UTC, AzulloCyll commented on packages/ui/ThreeDots/index.tsx
> +          <Icon icon="more_vert" />
You need to add color to icon. In our project it's not black.

2023-04-23 13:36 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +          <Icon icon="more_vert" />
thank you, I will fix that :)

2023-04-23 13:37 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +          {items.map((item, i) => {
good eye! On my way to fix it 👀

2023-04-23 16:50 UTC, Alessiass requested changes

2023-04-23 16:50 UTC, Alessiass commented on packages/ui/ThreeDots/index.tsx
> +} & React.HTMLProps<HTMLSelectElement>;
We should somehow pass the function for each of the items. Just string isn't enough.

2023-04-23 17:05 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +} & React.HTMLProps<HTMLSelectElement>;
@Alessiass  thank you for that comment. Why do you think of a function? Because if each of items will relocate user to another page I think that array of links would be accurate? I don't know the main idea of that so that's why i put this `Main question` in PR's comment 😄

2023-04-23 17:41 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +          <Icon icon="more_vert" />
@AzulloCyll done :)

2023-04-23 17:41 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +          {items.map((item, i) => {
@AzulloCyll done :)

2023-04-23 18:36 UTC, wyola reviewed
Looking good! on general note, I would change component's name simply to "DropdownMenu" or something more generic than "ThreeDots"? 🤔

2023-04-23 18:36 UTC, wyola commented on packages/ui/ThreeDots/index.tsx
> +  cursor: pointer;
why not throw in some nice styles here to spice it up a bit 🚀 I know there is no design, but you could make it look like this one:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/80450315/233856994-ca97cc52-0c8e-4c3c-84da-df8da697627d.png">

```suggestion
const DropdownMenuContentStyled = styled(DropdownMenu.Content)`
  margin-left: 8px;
  border: 1px solid #E1E1E1;
  box-shadow: 0px 2px 8px rgba(32, 37, 50, 0.08), 0px 2px 4px rgba(32, 37, 50, 0.03);
  border-radius: 16px;
  background-color: white;
  overflow: hidden;
`;

const DropdownMenuItemStyled = styled(DropdownMenu.Item)`
  padding: 8px;
  font-size: 14px;
  border-radius: 5px;
  cursor: pointer;
```
this way you arrive at this:

<img width="181" alt="image" src="https://user-images.githubusercontent.com/80450315/233857316-2276bebc-3767-4ad7-a4cb-5e94f7ac08fd.png">

nevertheless, you need to add at least `background-color: white;` on `DropdownMenuContentStyled` because right now it is transparent and upon opening it would not look good if there is anything under it 🤗

PS colors should come from the theme, I forgot about it here 🤭

2023-04-23 18:36 UTC, wyola commented on packages/ui/ThreeDots/index.tsx
> +} & React.HTMLProps<HTMLSelectElement>;
only `items` prop is used. I think that `React.HTMLProps<HTMLSelectElement>` can be removed

```suggestion
};
```

2023-04-23 18:36 UTC, wyola commented on packages/ui/ThreeDots/index.tsx
> +const DropdownMenuTriggerStyled = styled(DropdownMenu.Trigger)`
Right now, when the element is focused with keyboard there's no visual indication that it's active. Adding styles for `:focus` state (maybe an outline?) should fix it.

2023-04-23 18:36 UTC, wyola commented on packages/ui/ThreeDots/index.tsx
> +          <Icon icon="more_vert" color="#7E7E7E"/>
Use color from the theme

2023-04-23 18:36 UTC, wyola commented on packages/ui/ThreeDots/index.tsx
> +        <DropdownMenuContentStyled side="right">
maybe consider passing the position as a prop? I am thinking especially about mobile, when there probably won't be enough space on the right

2023-04-23 20:21 UTC, Alessiass commented on packages/ui/ThreeDots/index.tsx
> +} & React.HTMLProps<HTMLSelectElement>;
Just any function should do the job. It's not this dropdown menu's concern what the button will do. If we want to redirect to other path we will add something that will replace pathname, if we want to remove budget we will add fetch function and so on.

2023-04-23 23:22 UTC, monika-klokosinska-intive commented
@zuzannapaw since we don't have any idea what the menu under the the three dots will actually do 🙃 how about instead of passing `items` we will just render `children` as the dropdown submenu? This way we should be prepared for everything that might come our way - buttons, links, custom components etc,

2023-04-24 09:04 UTC, aniasgit commented on packages/ui/ThreeDots/index.tsx
> +} & React.HTMLProps<HTMLSelectElement>;
I agree with Bartek

2023-04-24 14:13 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +        <button>
Thank you @wyola for your comments and ideas with design! ✨  On my way to apply your suggestions!

2023-04-24 18:54 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +} & React.HTMLProps<HTMLSelectElement>;
@Alessiass @aniasgit I fixed this problem, now dropdown renders children inside itself. Currently children are created in `TransactionDropdownMenu.stories.tsx` and it's an array full of components. We can use any components that we like ☺️

2023-04-24 18:55 UTC, zuzannapaw commented on packages/ui/ThreeDots/index.tsx
> +        <button>
@wyola I have applied your suggestions - with code, design and component's name.

2023-04-24 19:31 UTC, aniasgit commented
> Storybook fails when I use `useTranslate` hook inside component - figuring out why.

useTranslate and dictionary are parts of web applications, they works with language contex, which is only in web application, not in storybook.

2023-04-24 19:49 UTC, wyola commented on packages/ui/TransactionDropdownMenu/index.tsx
> +`;
fix for focus outline on tab (you might adjust the thickness value though, I did not look into that)
```suggestion
const DropdownMenuTriggerStyled = styled(DropdownMenu.Trigger)`
  background-color: transparent;
  border: 0;
  cursor: pointer;

  &:focus {
    outline: ${({ theme }) => theme.transactionDropdownMenu.outlineFocus} 2px solid;
  }
`;
```

2023-04-24 19:56 UTC, zuzannapaw commented on packages/ui/TransactionDropdownMenu/index.tsx
> +`;
@wyola great, thank you, I have applied your fix!

2023-04-25 06:57 UTC, Alessiass approved these changes

2023-04-25 08:06 UTC, wyola commented on packages/ui/TransactionDropdownMenu/index.tsx
> +`;
if you change those styles like below:

```suggestion
export const DropdownMenuItemStyled = styled(DropdownMenu.Item)`
  padding: 6px 11px;
  font-size: 14px;
  cursor: pointer;  
  border: transparent 2px solid; 

  &:first-child {
    border-top-left-radius: 16px;
    border-top-right-radius: 16px;
  }

  &:last-child {
    border-bottom-left-radius: 16px;
    border-bottom-right-radius: 16px;
  }

  &:focus {
    border-color: ${({ theme }) => theme.transactionDropdownMenu.outlineFocus};    
  }

  &:hover {
    background: ${({ theme }) => theme.transactionDropdownMenu.backgroundHover};
    outline: 0;
  }
`;
```

there will be a nicer border effect on items when accessing the menu from keyboard:

https://user-images.githubusercontent.com/80450315/234214239-5a703bfb-8bd2-4cd5-a11b-8c5177154e5f.mp4

2023-04-25 08:12 UTC, monika-klokosinska-intive commented on packages/ui/TransactionDropdownMenu/index.tsx
> +`;
@zuzannapaw @wyola has some 💯 ideas here. We definitely need to add outlines for keyboard access, otherwise it looks un-accessible even though it is.

2023-04-25 08:18 UTC, bdeluga requested changes
Tell me what you think 🤔 👀

2023-04-25 08:18 UTC, bdeluga commented on packages/ui/TransactionDropdownMenu/index.tsx
I think the way you showcase component might be misleading to use. I don't think DropMenu should export its Item for other components to use. I was thinking maybe It should also expect us to recieve array of components to render.

![image](https://user-images.githubusercontent.com/79754698/234212614-ada49b59-5b2b-4745-b9f7-513623269976.png)

Then just map through components and render them in this component instead of just passing `children`

![image](https://user-images.githubusercontent.com/79754698/234213080-5fdd2ff6-1983-477e-8a30-56dd67f15b06.png)

This would be much easier for us to use - just passing items as object array instead of having to do all this array parkour. 

![image](https://media.tenor.com/6GIi9tonjeEAAAAd/parkour-the-office.gif)


### Usage 🚀 

![image](https://user-images.githubusercontent.com/79754698/234215719-e8c20af6-d795-40f5-b84f-0427da4094b3.png)

 ###  ❤️ Nontheless your solution isn't wrong, we could stick to it ❤️

2023-04-25 08:24 UTC, zuzannapaw commented on packages/ui/TransactionDropdownMenu/index.tsx
@bdeluga  thank you for your comments! Indeed that's a good solution - I have thought about it. But as @monika-klokosinska-intive  said, for now the dropdownmenu could accept `children` to be prepared for anything that will be rendered inside. Maybe in future, when we will know more details, it will be a good idea to make a component's refinement 👀 
<img width="740" alt="image" src="https://user-images.githubusercontent.com/93678778/234218455-0532b6c3-6df5-4831-a3c4-8ab96879763d.png">

2023-04-25 08:28 UTC, monika-klokosinska-intive commented on packages/ui/TransactionDropdownMenu/index.tsx
@zuzannapaw I was about to leave the same comment as @bdeluga :D. It's much better to just pass a `components` or `items` array without `DropDownMenuItemStyled`. 

`DropDownMenuItemStyled` should be added inside the map function. As a user of this component, I just want my array of stuff to be rendered inside the dropdown. I shouldn't have to know the inner workings of the drop down  (wrapping each item in `DropDownMenuItemStyled`, importing `DropDownMenuItemStyled`) to get that done.

Since `DropDownMenuItemStyled` has to be added to every item anyway, it makes it much simpler to do it inside the map. It will also make the actual usage of the component inside our app simpler - we won't have to add `DropDownMenuItemStyled` multiple times inside the `items` prop.

2023-04-25 08:30 UTC, monika-klokosinska-intive requested changes
@zuzannapaw Please take a look at the excellent suggestions by @bdeluga @wyola! Once they are applied and the conflicts are merged, we are good to go 👍

2023-04-25 08:47 UTC, bdeluga approved these changes
Approving ahead of time 🚀

2023-04-25 09:57 UTC, zuzannapaw commented on packages/ui/TransactionDropdownMenu/index.tsx
@bdeluga @monika-klokosinska-intive  thank you for your comments, I will fix it in a moment!

2023-04-25 12:10 UTC, zuzannapaw commented on packages/ui/TransactionDropdownMenu/index.tsx
@monika-klokosinska-intive @bdeluga  I have resolved conflicts and changed component as desired! Is it ready to merge?

2023-04-25 12:13 UTC, zuzannapaw commented on packages/ui/TransactionDropdownMenu/index.tsx
Although I can still see some problems with deployment :(

2023-04-25 12:50 UTC, wyola commented on packages/ui/TransactionDropdownMenu/index.tsx
> +`;
@zuzannapaw it's working great! sorry for being a pain! 🤗

2023-04-25 13:56 UTC, wyola commented on packages/ui/TransactionDropdownMenu/index.tsx
probably because of the limits on the vercel :( 

![image](https://user-images.githubusercontent.com/80450315/234299646-9d8fcc9a-897d-4a91-9d9e-b12fcef2a48b.png)

2023-04-25 14:08 UTC, monika-klokosinska-intive approved these changes

2023-04-25 14:09 UTC, merged