feat: info tile for basic budget information #P23-246
intive/patronage2023-js pull request #55
Opened 2023-04-23 18:51 UTC by PawelPazderski

## The Info Tile component for the budget basic information

Ticket for the task: https://tracker.intive.com/jira/browse/PATRO23-246

The component receives two type of props:

- `label` - which is a string
- displays information wchich can be a string or JSX Element as its `children` prop

### Example of usage:

Data:

```javascript
const exampleData = {
  dataToRender: (
    <>
      <Icon icon="subscriptions"/>
      <span>Awesome Icon</span>
    </>
  ),
  label: "Some Icon",
};
```

Code:
```javascript
<InfoTile label={exampleData.label}>{exampleData.dataToRender}</InfoTile>
```

Result: 

![image](https://user-images.githubusercontent.com/72406958/233858849-5217b8a4-ea85-4c29-8f53-47384e26e4a9.png)

---
*To see the live example of tiles rendered from dummy_data on this branch go to sign-up/playground*

2023-04-23 19:39 UTC, wyola reviewed
Looking good, just some minor styling issues. I am not sure about moving styles to a separate file - there is so little code that I don't know if it's necessary (unless we established that we should do it always, and I missed it 🫥)

2023-04-23 19:39 UTC, wyola commented on packages/ui/InfoTile/infoTile.styled.tsx
> +  padding: 16px 32px 16px 16px;
Correct the padding - top and bottom should be 8px

2023-04-23 19:39 UTC, wyola commented on packages/ui/InfoTile/infoTile.styled.tsx
> +  font-weight: 600;
add `margin-top: 4px;`

<img width="249" alt="image" src="https://user-images.githubusercontent.com/80450315/233860845-b6ba7aaf-934c-4765-b5af-f849260dc5df.png">

2023-04-23 19:39 UTC, wyola commented on packages/ui/InfoTile/infoTile.styled.tsx
> +  gap: 5px;
`gap` should be 8px I think 

<img width="367" alt="image" src="https://user-images.githubusercontent.com/80450315/233860930-d728edfc-bbad-403c-836f-58a896cf67e2.png">

2023-04-23 19:39 UTC, wyola commented on packages/ui/InfoTile/index.tsx
> +  children: string | JSX.Element;
you could change it like below, this way it includes both string and components (basically anything what React can render) -> https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/basic_type_example/#useful-react-prop-type-examples

```suggestion
  children: React.ReactNode;
```

2023-04-23 23:32 UTC, monika-klokosinska-intive commented on packages/ui/InfoTile/index.tsx
> +  children: string | JSX.Element;
@PawelPazderski instead of rendering `children`, try passing a component to render as a prop named `value` as the story specified (though admittedly the Jira story could use some polish). Zuza's `NavItem` inside `NavList` accepts `componentToRender` as a prop - this is the solution we are looking for here. 
I know it doesn't make that much difference in the end (component will work and look the same), but it's a good learning experience regardless.

2023-04-23 23:33 UTC, monika-klokosinska-intive commented
@PawelPazderski storybook deployment crashed - please look into it as it is a blocker for merging.

2023-04-24 09:07 UTC, PawelPazderski commented on packages/ui/InfoTile/infoTile.styled.tsx
> +  gap: 5px;
@wyola thanks a lot for all the suggestions, I'll do some style corrections taking them into mind

2023-04-24 11:49 UTC, monika-klokosinska-intive commented on packages/ui/InfoTile/index.tsx
> +export const InfoTile = ({ label, children }: InfoTileProps) => {
@PawelPazderski I apologise for not being clear enough. The only part of NavList I wanted lifted was the `dataToRender` part. So the component should be:
```
export const InfoTile = ({ label, dataToRender }: InfoTileProps) => {

  return (
    <InfoTileStyled>
      {label}
      <InfoValueWrapper>{dataToRender}</InfoValueWrapper>
    </InfoTileStyled>
  );
};
```

And the example props passed to InfoTile should look like this:

```
InfoTileDemo.args = {
  dataToRender: (
    <>
      <div style={{fontSize: "24px"}}>
        <Avatar src="/avatar.svg" />
      </div>
      
    </>
  ),
  label: "Some avatar",
}
```
We don't require a list of InfoTiles, so the `InfoTileList` is unnecessary. All we want here is a component `InfoTile` with props of `label` and `dataToRender`.

I am sorry for the extra work you did, I hope it was at least of educational value :).

2023-04-24 11:50 UTC, monika-klokosinska-intive requested changes
@PawelPazderski please take a look at my newest comment

2023-04-24 12:43 UTC, PawelPazderski commented on packages/ui/InfoTile/index.tsx
> +export const InfoTile = ({ label, children }: InfoTileProps) => {
Right no worries, I'll change that

2023-04-24 13:19 UTC, PawelPazderski commented on packages/ui/InfoTile/index.tsx
> +export const InfoTile = ({ label, children }: InfoTileProps) => {
OK, I guess the changes are done according to your suggestions, only problem is the fonts in storybook seem not to work when passing a complex structure - works fine with a string, in other cases the inheritance doesn't seem to work

2023-04-24 15:21 UTC, aniasgit commented on packages/ui/InfoTile/index.tsx
> +margin-top: 4px;
lack of spaces ;)

2023-04-24 16:29 UTC, PawelPazderski commented on packages/ui/InfoTile/index.tsx
> +margin-top: 4px;
thanks

2023-04-24 16:38 UTC, bdeluga approved these changes
Nice 🚀

2023-04-24 16:38 UTC, bdeluga commented
Got some conflicts to resolve 👀

2023-04-24 17:03 UTC, merged