feat: (Next-)Auth.js credentials log-in intergration #P23-196
intive/patronage2023-js pull request #58
Opened 2023-04-25 12:56 UTC by Alessiass

Jira task: [Link](https://tracker.intive.com/jira/browse/PATRO23-196)
Auth.js: [Link](https://authjs.dev/)

Requested features:
- Credentials provider should use email+password login
- Storage policy are cookies
- Refresh token integration
- Page securing middleware
- Setup of NEXTAUTH_SECRET

2023-04-27 14:50 UTC, wlechowicz requested changes

2023-04-27 14:50 UTC, wlechowicz commented on apps/web/pages/api/auth/[...nextauth].ts
> +          "https://inbudget-patronage-api-dev.azurewebsites.net/user/sign-in",
This should use `API_URL` env variable.

2023-04-27 14:50 UTC, wlechowicz commented on apps/web/pages/api/auth/[...nextauth].ts
> +        const user = await res.json();
Check `res.ok` before parsing because it will throw in the response is not a parseable JSON.

2023-04-27 14:50 UTC, wlechowicz commented on apps/web/pages/api/auth/[...nextauth].ts
> +    error: '"/sign-in/"',
Make this uniform, second one has no trailing slash, third one has quotes inside quotes.

2023-04-27 14:50 UTC, wlechowicz commented on apps/web/pages/api/auth/[...nextauth].ts
> +              accept: "text/plain",
Response is definitely not text/plain, but rather application/json. I don't think you need to set this at all.

2023-04-27 16:15 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +        const user = await res.json();
Fixed

2023-04-27 16:15 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +    error: '"/sign-in/"',
Fixed

2023-04-27 16:15 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +              accept: "text/plain",
Removed

2023-04-27 20:06 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +          "https://inbudget-patronage-api-dev.azurewebsites.net/user/sign-in",
Done, but the variable is missing in Vercel.

2023-04-28 07:40 UTC, bdeluga requested changes
Couple of tweaks 🚀

2023-04-28 07:40 UTC, bdeluga commented on apps/web/pages/api/auth/[...nextauth].ts
I am commenting on whole file so it is in one place. 📖 

- First of all you dont need async callbacks
- `async jwt` does nothing so we can get rid of it
- we could return just data we want not whole essay that backend returns to us
![image](https://user-images.githubusercontent.com/79754698/235083223-a70e3890-9143-442e-91e4-c583ff0bbcf3.png)
(ofc you have to update types acordingly, also retrieved sub, because TS want ID and yells at me, we dont like red in our IDE)
- we can just stick to one decode library 👷 
- storing accessToken in user is quite tricky, tRPC does this better cause it already has Default session for us to extend
![image](https://user-images.githubusercontent.com/79754698/235083767-aba5fea2-efe7-4522-b79f-ea459f015384.png)

- Logging In & Logging Off works without these, so i removed them
![image](https://user-images.githubusercontent.com/79754698/235083959-775a9101-c3fe-4eb4-a291-a8321a044f23.png)

- Since next-auth likes image instead of avatar i just gave up and changed it in types you made 🚀 
![image](https://user-images.githubusercontent.com/79754698/235084200-64d89304-4342-469f-892c-2c843586a302.png)

Results:
![image](https://user-images.githubusercontent.com/79754698/235085095-194bad16-ef4e-4dd1-9268-841c0b153252.png)

### Hope it helps 🙏

2023-04-28 16:50 UTC, bdeluga approved these changes
Nice job ! 🚀

2023-05-03 22:07 UTC, bdeluga requested changes

2023-05-03 22:07 UTC, bdeluga commented on apps/web/env.mjs
API_URL has to stay on client (and has to stay `NEXT_PUBLIC_`), because other components - that will be mainly "use client" sometimes needs to call api and your change will prevent them from it, here's my [conversation ](https://intive-apu8934.slack.com/archives/C04R6LM4JSV/p1682964811546359?thread_ts=1682962537.131399&cid=C04R6LM4JSV)with @wlechowicz for context.

❗ Client env will work on both server and client component

2023-05-04 03:26 UTC, Alessiass commented on apps/web/env.mjs
I understand but currently the API_URL on Vercel is very specific and will be only used by Next-Auth at this moment. Should I add another one on client and hide the login behind server or should we keep only the client one? Which would be better?

2023-05-04 06:52 UTC, wlechowicz commented on apps/web/env.mjs
As confirmed by the client, the backend URL is public and can be exposed. Vercel is already configured for `NEXT_PUBLIC_API_URL`.

2023-05-04 11:06 UTC, Alessiass commented on apps/web/env.mjs
Thanks for feedback! Fixed.

2023-05-04 15:10 UTC, bdeluga approved these changes
Nice job ! 🥇

2023-05-05 20:22 UTC, wlechowicz requested changes

2023-05-05 20:22 UTC, wlechowicz commented on turbo.json
> +      "env": ["API_URL"]
```suggestion
      "env": ["NEXT_PUBLIC_API_URL"]
```

2023-05-05 20:22 UTC, wlechowicz commented on apps/web/pages/api/auth/[...nextauth].ts
> +  },
Is this needed? This looks like the default behavior which I'd assume works out of the box. Question, not a strict change request.

2023-05-05 21:23 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +  },
@wlechowicz Currently it's not required. I added it because there was a point in story that we will use NEXT_SECRET env.
As according to: https://next-auth.js.org/configuration/options#override-jwt-encode-and-decode-methods
We can safely remove it.

2023-05-08 16:43 UTC, AzulloCyll commented on apps/web/app/(regflow)/sign-in/page.tsx
> +          email: values.email,
You don't need to asign result constant, because you don't using it in future. So just await signin..... will do the job.

2023-05-08 16:43 UTC, AzulloCyll commented on apps/web/app/(regflow)/sign-in/page.tsx
>              onSubmit={(e) => {
Line 85

I think you dont need `submit();` here. Submit function is going from Form Component by houseform.

2023-05-08 17:33 UTC, Alessiass commented on apps/web/app/(regflow)/sign-in/page.tsx
> +          email: values.email,
Fixed! 🚀

2023-05-08 17:33 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +    session({ session, token, user }) {
Fixed! 🚀

2023-05-08 17:33 UTC, Alessiass commented on apps/web/pages/api/auth/[...nextauth].ts
> +      async authorize(credentials, req) {
Fixed! 🚀

2023-05-08 19:38 UTC, zuzannapaw approved these changes
Just a small question! 👀 Great job 🚀

2023-05-08 19:38 UTC, zuzannapaw commented on apps/web/app/(regflow)/sign-in/page.tsx
> +      onSubmit={async (values) => {
Maybe if function passed in props is long, it would be good to move the declaration higher and just pass the function name in `onSumbit` ? What do you think?

2023-05-10 14:49 UTC, merged