Fix: Switch to Transient props in Logo component #P23-269
intive/patronage2023-js pull request #60
Opened 2023-04-26 14:20 UTC by AzulloCyll

Hello. I fixed problems with our logo wich was generating some console errors. Actually our console is clean. :)

Task: (https://tracker.intive.com/jira/browse/PATRO23-269

Problem is solved by changing original props to transient props in styled components. 
You can read about it [here](https://styled-components.com/docs/api#transient-props)

2023-04-26 14:53 UTC, monika-klokosinska-intive commented on packages/ui/Logo/index.tsx
>    /*
@AzulloCyll is this comment still relevant? If not, we could remove it.

2023-04-26 15:58 UTC, AzulloCyll commented on packages/ui/Logo/index.tsx
>    /*
@monika-klokosinska-intive 

It was added to just show logo on dark background in storybook when we had only storybook to show something on demo.

So I've got ridden of it, and added wrapper for the Logo in storybook. It works good :)

2023-04-26 16:28 UTC, aniasgit commented on packages/ui/Logo/index.tsx
> +  color: ${({ $white }) => ($white ? "white" : "#1E4C40")};
Why the colors are not from theme?

2023-04-26 16:30 UTC, aniasgit commented on packages/ui/Logo/index.tsx
> +  color: ${({ $white }) => ($white ? "white" : "#1E4C40")};
Why the colors are not from theme?

2023-04-26 16:55 UTC, AzulloCyll commented on packages/ui/Logo/index.tsx
> +  color: ${({ $white }) => ($white ? "white" : "#1E4C40")};
I'ts old component. I'll fix it of course.

2023-04-26 17:10 UTC, aniasgit approved these changes

2023-04-26 18:14 UTC, Noshi96 approved these changes
LGTM 🚀

2023-04-26 18:14 UTC, Noshi96 commented on packages/ui/Logo/index.tsx
> +  background-image: url(${({ $white }) => $white && logoVersions.white || logoVersions.color});
It's kinda hacky condition✍️ . Should also work within the use ternary operator. I think this will be easier to read :D 

```suggestion
  background-image: url(${({ $white }) => $white ? logoVersions.white : logoVersions.color});
```

2023-04-26 19:33 UTC, monika-klokosinska-intive commented on packages/ui/Logo/index.tsx
> +  background-image: url(${({ $white }) => $white && logoVersions.white || logoVersions.color});
Good point here by @Noshi96! @AzulloCyll could you apply? Afterwards we could merge this to main :).

2023-04-27 05:25 UTC, AzulloCyll commented on packages/ui/Logo/index.tsx
> +  background-image: url(${({ $white }) => $white && logoVersions.white || logoVersions.color});
Aplied, but unfortunately we exceeded our deploy limit on vercel. "...try again in 5 hours..." OMG, heavy penalty.

2023-04-29 08:06 UTC, bdeluga approved these changes
Nice job! 🚀 Those red errors had me scared 😱.

2023-05-01 23:59 UTC, wlechowicz requested changes

2023-05-01 23:59 UTC, wlechowicz commented on packages/ui/Logo/index.tsx
> +export const Logo = ({ $white, $logoWidth = 144 }: LogoProps) => {
That's not how this should work. The props should not be transient "on the outside", as in Logo component should accept `white` and `logoWidth` props, without the `$`. But it should use transient props inside, so that they don't get attached to DOM, so `<LogoSignet $logoWidth={logoWidth} $white={white} />`.

2023-05-02 08:07 UTC, AzulloCyll commented on packages/ui/Logo/index.tsx
> +export const Logo = ({ $white, $logoWidth = 144 }: LogoProps) => {
Ok, changes was made, and commited.

2023-05-03 16:16 UTC, Alessiass approved these changes

2023-05-05 21:07 UTC, wlechowicz approved these changes

2023-05-06 08:13 UTC, merged