Fix: transactions table #P23-282
intive/patronage2023-js pull request #68
Opened 2023-05-01 19:37 UTC by wyola

## Fixes for transactions' table
task: https://tracker.intive.com/jira/browse/PATRO23-282
### What changed ✏️ 
- **column sizes are set as %** - there is a difference in columns' width when you compare it to the design. This is due to the fact, that it has to display well on a variety of screen sizes. Setting it to widths similar to the ones on the design would always produce some problems on different widths, especially around breakpoints. I tried to find the best widths that work well on a bigger screen, around 1025px, and down to 768px. Below that we would need additional design and probably some columns should be hidden then.
- **other differences compared to design:**
   - as we discussed, the "Creator" column (header and contents) is centered (it is to the left in the design)
   - I centered also the "Amount" header (which seems to be to the left in the design), so there is a smaller gap between the header and column's contents. It could maybe be to the right, but on wider screens, it did not look good to have such a big white space between the "Status" and "Amount" headers
- **header bottom border** - I added styles to make it look like in the design (full width of the `Card`)
- **fix for table shift** - I fixed the table shift caused by `TransactionDropdownMenu` hiding the scrollbar
### Issues 😢 
It does not look great on a very wide screen. There probably should be some limits to `Card` width on such a screen, or some other way around it, but again, there is no design for that

<img width="949" alt="image" src="https://user-images.githubusercontent.com/80450315/235513962-d9c95c62-ad85-48f6-92a2-f1386a3f70b5.png">

### Things that might look weird but aren't 😅
- negative margins on `TableWrapper` - done to have a bottom border of the table header be of the full width of the `Card`
<img width="286" alt="image" src="https://user-images.githubusercontent.com/80450315/235515838-bfa0d70e-4c33-4456-accd-7367b64640ba.png">

- creating a grouping row adds an empty cell at the beginning of each row - it had to be sized to 1px instead of having `display: none` since the latter would for some reason shift the table layout to the left and add some space on the right 🙄
<img width="125" alt="image" src="https://user-images.githubusercontent.com/80450315/235516191-89ccd96c-f7a4-490c-8a38-44f07104ddc1.png">

- each column has a commented-out line that adds a background color to it, so it is easier to see how columns resize - I am leaving it for now, will remove it before merging

2023-05-01 23:51 UTC, wlechowicz requested changes
Right-aligned "Amount" cells look bad.

The whole table is unusable on mobile:
![obraz](https://user-images.githubusercontent.com/24250766/235550879-db49405d-a395-4aca-a977-9cdfeb7fff3d.png)

2023-05-02 09:08 UTC, wyola commented
> Right-aligned "Amount" cells look bad.
> 
> The whole table is unusable on mobile: 

@wlechowicz After asking clients, I changed "Amount" to be aligned to the left (https://intive-apu8934.slack.com/archives/C04R6LM4JSV/p1683016578103229)

As for the mobile design - I thought we talked that there is no design for those screens, therefore we do not work on it now. Like I wrote in the PR's description:

> I tried to find the best widths that work well on a bigger screen, around 1025px, and down to 768px. **Below that we would need additional design and probably some columns should be hidden then.**

So should I hide some columns below 768px? Set the table to have min-width of that value so there is a horizontal scroll?

2023-05-04 16:56 UTC, Alessiass approved these changes
Looks and works really nice! 🚀

2023-05-04 19:20 UTC, wlechowicz approved these changes

2023-05-05 09:06 UTC, merged