feat: env stuff 📦
intive/patronage2023-js pull request #69
Opened 2023-05-01 19:38 UTC by bdeluga

## Introducing **[T3.env](https://env.t3.gg)** 👷‍♂️ 

Zod library that help us solve env problems when even rubber duck cannot. ✨ 

## Env schema :page_with_curl:

First we create .mjs file and create our env schema.

 ⚠️Note that demo shows `client-side` env - it has to be prefixed with NEXT_PUBLIC_. 
```tsx
//env.mjs

import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  client: {
    NEXT_PUBLIC_SOME_KEY: z.string().url(),
  },

  runtimeEnv: {
    NEXT_PUBLIC_API_URL: process.env["NEXT_PUBLIC_SOME_KEY"],
  },
});

```
Since we are using next.js `runtimeEnv` is strict by default  and we have to destructure process ourselves.

## Setting env variable 🔨 

```tsx
//.env.local

NEXT_PUBLIC_SOME_KEY="Q2FrZSBpcyBhIGxpZQ=="

```

## Usage  🎯 

```tsx

//Budgets.tsx

import {env} from "@/env.mjs" //same import on both server and client side

const res = fetch(env.NEXT_PUBLIC_SOME_KEY).then(...)

```

## Disclaimer 🚧 

Since every bone of my body stops me from posting **ANY** api url in github. As a good practise let's keep .env.local in `.gitignore` and please add `API_URL` in your .env.local. Dont forget about `NEXT_PUBLIC_`. 🚀

2023-05-01 23:43 UTC, wlechowicz requested changes
LGTM, but please add NEXTAUTH_SECRET env var since we have that too.

2023-05-01 23:46 UTC, wlechowicz approved these changes
Never mind, it's still an open PR that env var.

2023-05-02 09:07 UTC, Vectari approved these changes

2023-05-02 18:34 UTC, Alessiass approved these changes

2023-05-03 09:25 UTC, monika-klokosinska-intive approved these changes

2023-05-03 10:12 UTC, merged