feature/P23-40-edit-budget
intive/patronage2023-js pull request #70
Opened 2023-05-01 21:41 UTC by mpiwonski

Hi all,
That wil be a draft pull request for the time being as still there is a few things that need to be discussed.

1. As I mentioned in Slack, there's an issue with **type compatibility for `Budget`**. There's 2 types defined, which are slightly different to each other and each requires some code modifications for an app to work accordingly.

2. There's a create budget endpoint that can already be accessed, whereas there's a question whether we should also have a separate one for editing budget (PATCH?). As for now - budgets state is updated once a specific budget has been changed, so the modifications are immediately presented in the interface.

2023-05-02 00:14 UTC, wlechowicz commented
Deployment fails due to the type problem mentioned in the description.
![obraz](https://user-images.githubusercontent.com/24250766/235553253-f05b112c-4871-46e9-8b6f-8483a0871913.png)

2023-05-03 09:12 UTC, AzulloCyll reviewed
![image](https://user-images.githubusercontent.com/65503275/235873455-34885ebc-3041-4ddb-81b5-100c97361191.png)

That error is showing when you delete a Date. It means that you can't execute function `.getTime()` on null.
You can get my handler for this situation from `createNewBudget` which prevents getTime from calling in certain situation.

![image](https://user-images.githubusercontent.com/65503275/235874432-c2d0d52f-972e-4073-90b4-da728ea1a417.png)

or just simply get rid of X button from input. But this case should be discussed.

You can show data object wich will be sent to backend in console after you click "Save" button.

2023-05-03 10:28 UTC, AzulloCyll requested changes

2023-05-03 10:28 UTC, AzulloCyll commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +                onClose();
When you add onClose here, validation will not goes in. 
Check it on AddNewBudgetModal when all fields in form are empty.

2023-05-04 09:02 UTC, mpiwonski commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +                onClose();
Thanks for your insights. Fixed.

2023-05-04 09:04 UTC, mpiwonski commented
> ![image](https://user-images.githubusercontent.com/65503275/235873455-34885ebc-3041-4ddb-81b5-100c97361191.png)
> 
> That error is showing when you delete a Date. It means that you can't execute function `.getTime()` on null. You can get my handler for this situation from `createNewBudget` which prevents getTime from calling in certain situation.
> 
> ![image](https://user-images.githubusercontent.com/65503275/235874432-c2d0d52f-972e-4073-90b4-da728ea1a417.png)
> 
> or just simply get rid of X button from input. But this case should be discussed.
> 
> You can show data object wich will be sent to backend in console after you click "Save" button.

Thanks for your insights. Eventually I combined your Budget type with @bdeluga Budget type, which also implied a need to change one of the functions related to timestamp in BudgetBasicInfo, and now it seems it works appropriately :)

2023-05-04 11:03 UTC, AzulloCyll approved these changes

2023-05-04 12:43 UTC, aniasgit commented on packages/ui/EditIcon/index.tsx
> +  color: #7e7e7e;
add colors from theme

2023-05-04 12:46 UTC, aniasgit commented on packages/ui/index.tsx
> +import { EditIcon } from "./EditIcon";
You don't need to import it here.

2023-05-04 12:48 UTC, aniasgit commented on packages/ui/EditIcon/index.tsx
> +const EditIconStyled = styled.span`
If we want to click on it, there should probably be a button.

2023-05-04 16:38 UTC, Noshi96 commented on apps/web/app/(navigation)/EditBudget.tsx
> +  const [defaultValueTabs, setDefaultValueTabs] = useState("settings");
I think we don't need to useState for defaultValue, because it appears only once, and we don't expect its value to change dynamically. You can simply write `const defaultValueTabs = "settings"` above the component declaration imo :D

2023-05-05 16:58 UTC, mpiwonski commented on packages/ui/EditIcon/index.tsx
> +const EditIconStyled = styled.span`
Thanks for your insight. Fixed :)

2023-05-05 16:59 UTC, mpiwonski commented on apps/web/app/(navigation)/EditBudget.tsx
> +  const [defaultValueTabs, setDefaultValueTabs] = useState("settings");
Fair point :)

2023-05-05 17:01 UTC, mpiwonski commented on apps/web/app/(navigation)/budgets/BudgetsContent.tsx
> +  const showEditBudgetModal = () => {
Right, but showEditBudgetModal/hideEditBudgetModal are used in different places with, and I think it's good to leave them separated, and each component receives a specific method according to their needs and it's semanticly clear.

2023-05-05 17:06 UTC, mpiwonski commented on packages/ui/EditIcon/index.tsx
> +import { Icon, IconType } from "../Icon";
Done.

2023-05-05 17:07 UTC, mpiwonski commented on packages/ui/index.tsx
> +import { EditIcon } from "./EditIcon";
It was by mistake. Fixed.

2023-05-05 17:07 UTC, mpiwonski commented on packages/ui/EditIcon/index.tsx
> +  color: #7e7e7e;
Done.

2023-05-05 21:03 UTC, wlechowicz requested changes
Overall, in EditBudget component, there's too much inline logic in JSX and most of it should be placed above, so that the JSX (return) focuses more on the layout, and the business logic - functions, evaluations - are in the body of the component, before the return.

2023-05-05 21:03 UTC, wlechowicz commented on apps/web/lib/dictionary.tsx
> +        pl: "Nazwa musi mieć conajmniej 3 znaki.",
```suggestion
        pl: "Nazwa musi zawierać co najmniej 3 znaki.",
```

2023-05-05 21:03 UTC, wlechowicz commented on apps/web/lib/dictionary.tsx
> +        pl: "Ustawiena",
```suggestion
        pl: "Ustawienia",
```

2023-05-05 22:17 UTC, Noshi96 commented on apps/web/app/(navigation)/budgets/BudgetsContent.tsx
> +  const showEditBudgetModal = () => {
Yep I agree with you :D

2023-05-06 12:10 UTC, mpiwonski reviewed
Thanks @wlechowicz for all your remarks and suggestions. I have included them in recent code changes. I have also got rid of `editBudget` state as now we only depend on the values avaiable after form submission. It definitely made code more neat and functional. Please take a look at latest changes and let me know if it's OK or there's anything I could improve :)

2023-05-06 12:52 UTC, wyola commented on packages/ui/EditIcon/index.tsx
> +};
you could cut this code a bit ✂️ 
- with few changes to `EditIconStyled` you don't need the `Wrapper`
- `Icon` has a `color` prop that you could use

```suggestion
const EditIconStyled = styled.button<EditIconInterface>`
  cursor: pointer;
  border: none;
  background-color: ${({ theme }) => theme.editIcon.background};
  height: 2.5em;
  width: 2.5em;
  border-radius: 8px;
  flex-shrink: 0;
  line-height: 0;
`;

export const EditIcon = ({ onClick }: EditIconInterface) => {
  const theme = useContext(ThemeContext);
  return (
    <EditIconStyled onClick={onClick}>
        <Icon icon="edit" color={theme.editIcon.main}/>
    </EditIconStyled>
  );
};
```
`flex-shrink` is there so that button does not shrink when page is resized ⬇️ (now I actually noticed that `BudgetIcon` has this issue 👀 )
 
![image](https://user-images.githubusercontent.com/80450315/236624521-9d76065a-d769-461d-bbf0-f6e253c2043e.png)

PS you have to add to imports to use color prop
`import styled, { ThemeContext } from "styled-components";`
`import { useContext } from "react";`
and to component
`const theme = useContext(ThemeContext);`

2023-05-07 13:56 UTC, zuzannapaw reviewed
Good job! Although I'm wondering why the modal does not show up in the middle of the page, but it's moved a bit on the left. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93678778/236681786-bca7642b-2ffd-46b7-9fab-015c0e922395.png">

2023-05-07 13:56 UTC, zuzannapaw commented on apps/web/app/(navigation)/EditBudget.tsx
> +    form: FormInstance<any>
Could you tell me why did you use here `any` type? 🤔

2023-05-07 13:56 UTC, zuzannapaw commented on apps/web/app/(navigation)/EditBudget.tsx
> +                <Tabs.Content value="share">Welcome to share</Tabs.Content>
I think this should come from dictionary as well 😃

2023-05-07 16:34 UTC, AzulloCyll commented on apps/web/app/(navigation)/EditBudget.tsx
> +                <Tabs.Content value="share">Welcome to share</Tabs.Content>
No, please don't change this. It's only placeholder!! :)

2023-05-08 07:12 UTC, zuzannapaw commented on apps/web/app/(navigation)/EditBudget.tsx
> +                <Tabs.Content value="share">Welcome to share</Tabs.Content>
Okay!! @AzulloCyll

2023-05-08 15:52 UTC, wyola commented on apps/web/app/(navigation)/EditBudget.tsx
> +  };
I think that there are a few things here that are a little confusing, because of the variables' names used 👀 

For example, there is `const end` but it regards `start-date`, and `start` variable is really the timestamp of end date. As a result, because of the current names of the variables, the "if" statement: `if (start < end)` at first glance makes you wonder why there is an error for a situation when `start < end`.

I also think that you can simplify code for `start` and `end` variables using `?` operator.

To sum up, after changing variables' names and mentioned above simplifaction you could arrive at this:

```suggestion
  const checkEndDateOnChangeValidate = (
    endDateValue: Date | null,
    form: FormInstance<any>
  ) => {
    const endTimestamp = endDateValue?.getTime();
    const startTimestamp = form.getFieldValue("start-date")!.value?.getTime();

    if (endTimestamp && startTimestamp) {
      if (startTimestamp > endTimestamp) return Promise.reject(t(dict.errors.dateBeforeStart));
    }
    return Promise.resolve(true);
  };
```

2023-05-09 11:17 UTC, mpiwonski commented on apps/web/app/(navigation)/EditBudget.tsx
> +    form: FormInstance<any>
Hi @zuzannapaw, I've been trying to look up default type of `(val, form)` in houseform docs, but it seems I cannot find them, however it was suggested in VSCode, so the types would be compatible and there would not be TS error.

2023-05-09 11:22 UTC, mpiwonski commented on apps/web/app/(navigation)/EditBudget.tsx
> +                    <Field
Hi @wyola, honestly, I do not have anything against the current way it is displayed now, especially it's also present in create budget form that was created by @AzulloCyll, so he should also be included in the conversation.

2023-05-12 16:27 UTC, PawelPazderski approved these changes
LGTM to merge and continue from here with BE integration 🚀

2023-05-12 16:42 UTC, AzulloCyll commented
@PawelPazderski 
Description is not required so can be empty. :)

2023-05-12 19:01 UTC, Alessiass requested changes

2023-05-14 09:37 UTC, AzulloCyll commented on apps/web/app/(navigation)/EditBudget.tsx
> +              }}>
done :)

2023-05-14 10:04 UTC, Alessiass approved these changes

2023-05-15 08:01 UTC, aniasgit commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +                          form.getFieldValue("start-date")!.value.getTime();
Since we use ISOString to communicate with BE, getTime() is no longer needed. DatePicker returns values, in the Date type, which you can compare, and before sending to the backend, you just need to convert them to ISOString (toISOString()).

2023-05-15 08:11 UTC, aniasgit reviewed
I believe all date operations should be changed, we don't need dates in timestamps anymore. All operations on dates can be performed on Date objects returned to us by DatePicker, and before sending to BE, the values should be converted to ISOString. Similarly, date values that we get from BE should be converted to Date for further operations on them.

2023-05-15 11:46 UTC, aniasgit approved these changes

2023-05-15 18:45 UTC, wlechowicz approved these changes
LGTM overall, one refactor to be made based on inline comment.

2023-05-15 18:45 UTC, wlechowicz commented on apps/web/app/(navigation)/EditBudget.tsx
> +    <Modal header={t(dict.title)} onClose={() => onClose()} fullHeight>
```suggestion
    <Modal header={t(dict.title)} onClose={() => onClose && onClose()} fullHeight>
```

2023-05-15 19:55 UTC, merged