feat: integrate create new budget backend #P23-291
intive/patronage2023-js pull request #81
Opened 2023-05-08 21:35 UTC by Vectari

### Hello! Here is PR of my task [P23-291](https://tracker.intive.com/jira/browse/PATRO23-291).
1. Because for now working Currency from BE is only USD and EUR I left only this two in Currency Select list.
2. I use uuid to generate individual `id`.

## How to use:
1. Use `npm i`
2. Go to [Swagger](https://inbudget-patronage-api-dev.azurewebsites.net/swagger/index.html) and use `{
  "email": "smutnarzaba@png.pl",
  "password": "Frytki123.FE"
}` in `/user/sign-in`
3. Copy token to **_133_** line of my code and then `npm run dev`
4. After you create new budget in app and **Authorize in Swagger** go to `/budgets/list` and use `{
  "pageSize": 20,
  "pageIndex": 1,
  "search": "budget",
  "sortDescriptors": [
    {
      "columnName": "name",
      "sortAscending": true
    }
  ]
}
` to show budget list. Change `pageSize` if longer list is needed.
5. Copy `id` value and paste in `budgets/{id}` if you want check budget detail.

### I still don't have errors because I have some question to ask in next Teams Meeting but Create Budget is working and Demo is coming so main part of task is most important for now.

## Have a great day! 😁

2023-05-08 23:12 UTC, bdeluga requested changes
Small things to improve. 📖

2023-05-08 23:12 UTC, bdeluga commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const queryClient = useQueryClient();
We are already creating one instance of queryClient in RootLayout, so this line is redundand.

2023-05-08 23:12 UTC, bdeluga commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +        onError: () => {},
Maybe, let's at least console.log if any error do happen. 😵

2023-05-08 23:12 UTC, bdeluga commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const url = "https://inbudget-patronage-api-dev.azurewebsites.net/budgets";
#69 is already on main, please use .env for that 📦

2023-05-09 09:19 UTC, wyola commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +          }),
You are using string interpolation on every value here, while everything, except the value, is a string already. And value should be sent to the backend as a number, so also not needed here.

```suggestion
          body: JSON.stringify({
            id: uuidv1(),
            name: newBudget.name,
            userId: uuidv1(),
            limit: {
              value: newBudget.limit,
              currency: newBudget.currency.tag,
            },
            period: {
              startDate: budgetStartDate,
              endDate: budgetEndDate,
            },
            description: newBudget.description,
            iconName: newBudget.icon,
          }),
```

2023-05-09 10:01 UTC, aniasgit commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +import { v1 as uuidv1 } from "uuid";
why did you choose timestamp uuid not a random one (v4)?

2023-05-09 14:19 UTC, PawelPazderski commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
Also, I think we should use one date format same for every place, like we got day/month/year in the tile:
![image](https://github.com/intive/patronage2023-js/assets/72406958/5dba0c7a-fa2f-43f1-aebf-492e313ab440)
when in the date picker is month/day/year:
![image](https://github.com/intive/patronage2023-js/assets/72406958/79351baa-76fb-4e63-a416-66ba875fa409)

2023-05-09 14:51 UTC, aniasgit commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
It should depend on locale

2023-05-09 15:01 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
@aniasgit is right about the datetime manipulation. You absolutely don't want to manage timezones etc. by hand. That path leads straight to hell. It's fine to transform one date type into another (e.g. from timestamp to ISOString if that' what the backend wants), but dealing with timezones is best left to an existing JS utility / library.

2023-05-09 15:11 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
You are probably right, but i think it should be new task to fix/refactor datepicker. Here I just integrate Create New Budget with BE. Of course, I can do that if this task is the place for such correction. About that 2 hours. I did this in that way because without it when you pick for example 10 June budget send to BE 9 June, time 22:00. I know it’s wild but I was thinking if time is not important for us so I can make it in that way. I try other way than :)

2023-05-09 15:17 UTC, AzulloCyll commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
> Also, I think we should use one date format same for every place, like we got day/month/year in the tile: ![image](https://user-images.githubusercontent.com/72406958/237123708-5dba0c7a-fa2f-43f1-aebf-492e313ab440.png) when in the date picker is month/day/year: ![image](https://user-images.githubusercontent.com/72406958/237124065-79351baa-76fb-4e63-a416-66ba875fa409.png)

You can change datepicker date format in CustomDatepicker component in ui. 
![image](https://github.com/intive/patronage2023-js/assets/65503275/e5eb5a5b-e989-44e4-883e-00d374ed490e)

2023-05-09 15:27 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
Yes I know. I change it too then

2023-05-09 21:20 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const queryClient = useQueryClient();
I think it's required for onSuccess but I will back to onSuccess and onError tomorrow and check.

2023-05-09 21:22 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +        onError: () => {},
I add error tomorrow 🙃

2023-05-09 21:22 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const url = "https://inbudget-patronage-api-dev.azurewebsites.net/budgets";
Done :)

2023-05-09 21:23 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +          }),
Done :)

2023-05-09 21:26 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +import { v1 as uuidv1 } from "uuid";
I changed to v4. Later uuid will be deleted because we dont have to generate and send ID but for now request without ID not work in BE.

2023-05-09 21:28 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
I deleted +2h and change Date Picker to dd/MM/yyyy. Hope everything is good now 😄

2023-05-10 00:33 UTC, Noshi96 commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +import { v1 as uuidv1 } from "uuid";
@Vectari Btw, you actually don't need to add external libs to generate v4 uuid. You can use the native JS function 🚀  https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

2023-05-10 05:25 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +import { v1 as uuidv1 } from "uuid";
You are right. I changed to this one 👍

2023-05-11 12:38 UTC, aniasgit commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const budgetEndDate = new Date(endDateTimeStamp).toISOString();
It won't be needed if https://github.com/intive/patronage2023-js/pull/81/files#r1191108946

2023-05-11 12:44 UTC, aniasgit commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  const queryClient = useQueryClient();
This queryClient will be needed for invalidate budgets.

2023-05-11 12:44 UTC, bdeluga approved these changes

2023-05-11 12:59 UTC, Vectari commented on apps/web/app/(navigation)/CreateNewBudget.tsx
> +  dateEnd: any;
I will try but I can't make it before demo 😕

2023-05-11 13:05 UTC, merged