feat: create new income and expense #P23-232
intive/patronage2023-js pull request #82
Opened 2023-05-09 08:27 UTC by aniasgit

task: [](https://tracker.intive.com/jira/browse/PATRO23-232)

What is done:

- form for creating new transactions,
- category selector

To do:
-integration with BE,
-notifications about success or failure when adding a transaction (I probably won't be able to do it in this sprint)

2023-05-09 09:27 UTC, PawelPazderski approved these changes
Looks and works very nice, good job! The only thing that bothers me while interacting is the jumping effect caused by disabling the scrollbar "the modal mode" when opening Select for a category, in Dropdown it was possible to set it as `modal={false}` but can't see that for Select which would be cool here as well. 
![image](https://user-images.githubusercontent.com/72406958/237054062-ac0acefc-d05d-4054-b596-c9a1a66007a4.png)

There is also an error in console:
![image](https://user-images.githubusercontent.com/72406958/237054500-b2a5a145-fae4-4143-a7b5-b5506e3484c5.png)

2023-05-09 09:33 UTC, wyola commented
> Looks and works very nice, good job! The only thing that bothers me while interacting is the jumping effect caused by disabling the scrollbar "the modal mode" when opening Select for a category, in Dropdown it was possible to set it as `modal={false}` but can't see that for Select which would be cool here as well. ![image](https://user-images.githubusercontent.com/72406958/237054062-ac0acefc-d05d-4054-b596-c9a1a66007a4.png)
> 
> There is also an error in console: ![image](https://user-images.githubusercontent.com/72406958/237054500-b2a5a145-fae4-4143-a7b5-b5506e3484c5.png)

@PawelPazderski there is a fix for the jumping effect on @Noshi96 's branch, it will be changed in global CSS 👉 https://github.com/intive/patronage2023-js/pull/71#discussion_r1187704186

2023-05-09 09:49 UTC, PawelPazderski commented
> > Looks and works very nice, good job! The only thing that bothers me while interacting is the jumping effect caused by disabling the scrollbar "the modal mode" when opening Select for a category, in Dropdown it was possible to set it as `modal={false}` but can't see that for Select which would be cool here as well. ![image](https://user-images.githubusercontent.com/72406958/237054062-ac0acefc-d05d-4054-b596-c9a1a66007a4.png)
> > There is also an error in console: ![image](https://user-images.githubusercontent.com/72406958/237054500-b2a5a145-fae4-4143-a7b5-b5506e3484c5.png)
> 
> @PawelPazderski there is a fix for the jumping effect on @Noshi96 's branch, it will be changed in global CSS 👉 [#71 (comment)](https://github.com/intive/patronage2023-js/pull/71#discussion_r1187704186)

2023-05-09 10:21 UTC, wyola commented on apps/web/app/(navigation)/budgets/CreateNewTransaction.tsx
> +                      name="amount"
"Amount" input does not focus when clicking on label. It is because `id` for it is created based on `name` and it is not unique within the page - ka-table creates id "amount" based on column's name. So you either need to change name here or add id prop with unique value.

2023-05-09 16:18 UTC, wyola reviewed
Few things related mostly to code repetition in styles. Idk if maybe you were in a hurry and intend to change this later, I will just leave it here.

On general note, I think that `select` should be an atomic component and serve both for Currency and Categories

2023-05-09 16:18 UTC, wyola commented on apps/web/app/(navigation)/budgets/CategorySelector.tsx
> +import categoryMap from "../../../lib/category-map";
```suggestion
import categoryMap from "lib/category-map";
```

2023-05-09 20:47 UTC, Noshi96 commented
> > Looks and works very nice, good job! The only thing that bothers me while interacting is the jumping effect caused by disabling the scrollbar "the modal mode" when opening Select for a category, in Dropdown it was possible to set it as `modal={false}` but can't see that for Select which would be cool here as well. ![image](https://user-images.githubusercontent.com/72406958/237054062-ac0acefc-d05d-4054-b596-c9a1a66007a4.png)
> > There is also an error in console: ![image](https://user-images.githubusercontent.com/72406958/237054500-b2a5a145-fae4-4143-a7b5-b5506e3484c5.png)
> 
> @PawelPazderski there is a fix for the jumping effect on @Noshi96 's branch, it will be changed in global CSS 👉 [#71 (comment)](https://github.com/intive/patronage2023-js/pull/71#discussion_r1187704186)

Indeed, the solution was given, but it is slightly different. The problem was that the scrollbar from radix was forced to be removed when the option was opened. Now, there is a custom hook that checks if we have an active scrollbar on the page. Please add the lines below to `CategorySelector.tsx` and the problem goes away.  

```js
const { hasScrollbar } = useHasScrollBar();
```

```js
<SelectPortalStyled className={hasScrollbar ? "radix-scroll" : "">
  <SelectContentStyled position="popper">
    <Select.Viewport>
```

The magic happened here, in `global.css` where we force the scroll bar to be maintained when the options were opened, when class `radix-scroll` was included:

```css
body:has(.radix-scroll) {
  @media only screen and (min-width: 768px) {
      overflow-y: scroll !important;
  } 
}
```

2023-05-10 14:30 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/budgets/CategorySelector.tsx
> +            {/* {categories.map((category) => (
@aniasgit if you don't need this piece of code anymore, you can remove it altogether.

2023-05-10 14:31 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/budgets/CategorySelectorStyled.tsx
> +export const SelectTriggerStyled = styled(Select.Trigger)<{
@wyola one component for both might not work, since the behaviour is different, but it would be good to re-use thee styles in both places if possible.

2023-05-10 17:48 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/CreateNewTransactionStyled.tsx
> +`;
I agree that a lot of styles are duplicated, but these are styles for separate forms. I don't want the style changes in createNewBudget to affect the appearance of my form.

2023-05-11 08:00 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/CreateNewTransaction.tsx
> +                      name="amount"
changed name

2023-05-11 08:11 UTC, aniasgit commented
> Few things related mostly to code repetition in styles. Idk if maybe you were in a hurry and intend to change this later, I will just leave it here.
> 
> On general note, I think that `select` should be an atomic component and serve both for Currency and Categories

I agree that select should be an atomic component. When I was creating it, I suggested Wojtek's statement that it is part of the form and I placed it next to the form. I think I could move it to the ui and let it take whatever components we want, but it requires some changes. I don't want to do it before the demo. However, it will not be the same select for currency and category, because in currency there is a bit of a custom display of the selected value (the tag itself)

2023-05-11 08:13 UTC, aniasgit commented on packages/ui/theme.tsx
> +  categorySelect: {
If we decided to do separate objects in theme form separate components I think we should stay with this method.

2023-05-11 08:13 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/CreateNewTransactionStyled.tsx
> +  color: #515151;
done

2023-05-11 08:14 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/CreateNewTransactionStyled.tsx
> +  grid-row-end: 2;
removed

2023-05-11 08:15 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/CategorySelectorStyled.tsx
> +export const SelectTriggerStyled = styled(Select.Trigger)<{
similar to this https://github.com/intive/patronage2023-js/pull/82#discussion_r1190229252

2023-05-11 08:19 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/CategorySelector.tsx
> +            {/* {categories.map((category) => (
removed

2023-05-11 13:04 UTC, wlechowicz commented
Review authors, it is on you to resolve conversations that are done. @monika-klokosinska-intive @wyola and everyone.

2023-05-11 15:33 UTC, bdeluga approved these changes
If it builds, it can be merged 🚀

2023-05-11 15:43 UTC, Noshi96 approved these changes

2023-05-11 20:16 UTC, wlechowicz requested changes

2023-05-11 20:16 UTC, wlechowicz commented on apps/web/lib/dictionary.tsx
> +        fr: "Le nom ne peut pas dépasser 58 caractères.",
If requirement changes to be 59 instead of 58 chars, it would be a lot of changes here and in the component. Instead, this should just be a function that takes the number and puts it into the error string `Name must not have more than ${length} characters.`

2023-05-16 11:11 UTC, wlechowicz commented on apps/web/lib/dictionary.tsx
> +        fr: "Le nom ne peut pas dépasser 58 caractères.",
As discussed, since this is done this way in multiple places, we should aim to improve this solution in a separate, refinement task.

2023-05-16 12:22 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/budgets/[id]/CreateNewTransaction.tsx
> +        // queryClient.invalidateQueries(["datatable"]);
@aniasgit we gonna add the invalidation back in!

2023-05-16 12:25 UTC, monika-klokosinska-intive requested changes
@aniasgit since the main "meat" of this PR is already merged, please follow up with a refinement PR addressing the requested changes.

2023-05-17 17:05 UTC, closed without merging