feat: trend chip #P23-309
intive/patronage2023-js pull request #83
Opened 2023-05-10 08:20 UTC by zuzannapaw

ticket: https://tracker.intive.com/jira/browse/PATRO23-309

<h3>Overview 👀 </h3>
Trend chip component that accepts value in props. Depending on a positive or negative value, it takes proper color and icon.
 
```typescript
export type TrendChipProps = {
  value: number;
} & React.HTMLProps<HTMLDivElement>;
```  

<h3>Problem 🤔 </h3>

I tried to imagine a situation where user can get really high income, and then value could be quite long. In that situation, even though TrendChip doesn't have width, but only paddings, the value goes beyond it's border. Now this problem is caused by wrapper in storybook, so the width depends on parent element. Should it be that way, or maybe we need to find another solution?

<h3>Component's design: </h3>

<img width="70" alt="image" src="https://github.com/intive/patronage2023-js/assets/93678778/e514f5f7-8fde-4512-a90b-af2fbc9b6fb7">
<img width="71" alt="image" src="https://github.com/intive/patronage2023-js/assets/93678778/d77f28b8-eb91-4692-a49e-148346da85c7">

2023-05-10 08:48 UTC, bdeluga approved these changes
LGTM! 🚀

2023-05-10 09:00 UTC, monika-klokosinska-intive requested changes
@zuzannapaw You are missing the third use case mentioned in the ticket: gray colors and flat arrow (line if there is no arrow?) when the passed value equals zero. 
There is no design for this usecase so you have to use your creativity ;).

2023-05-10 11:19 UTC, Noshi96 approved these changes
With `width: fit-content` mentioned by @monika-klokosinska-intive will be perfect. Well done! 🚀  🚅

2023-05-10 11:19 UTC, Noshi96 commented on packages/ui/TrendChip/index.tsx
> +};
```suggestion
export const TrendChip = ({ value }: TrendChipProps) => {
  const iconName = (): IconType => {
    if (value === 0) return "trending_flat";
    if (value < 0) return "trending_down";
    return "trending_up";
  };
  return (
    <TrendChipStyled value={value}>
      <Icon icon={iconName()} iconSize={15} />
      <span>{Math.abs(value)}%</span>
    </TrendChipStyled>
  );
};
```

I think we can simplify it. What do you think?

2023-05-10 11:19 UTC, Noshi96 commented on packages/ui/TrendChip/index.tsx
> +  font-weight: 600;
```suggestion
  font-size: 12px;
  padding: 4px 8px;
  font-weight: 600;
```

2023-05-10 11:19 UTC, Noshi96 commented on packages/ui/TrendChip/index.tsx
> +    value > 0 ? <span>{value}%</span> : <span>{Math.abs(value)}%</span>;
I wonder if we need some aria role status here, for example 🤔 https://stackoverflow.com/questions/68170589/do-html-elements-like-pill-badge-need-extra-aria-role

2023-05-10 18:37 UTC, wlechowicz commented
Doesn't look quite right in the storybook preview (vertical misalignment):
![image](https://github.com/intive/patronage2023-js/assets/24250766/ca3148d4-e855-4dc6-ba9b-e4eb5f4a7723)

2023-05-10 18:40 UTC, zuzannapaw commented on packages/ui/TrendChip/index.tsx
> +};
Great remark! On my way to apply it!

2023-05-10 18:40 UTC, zuzannapaw commented on packages/ui/TrendChip/index.tsx
> +export const TrendChipStyled = styled.div<TrendChipProps>`
Thank you so much! On my way to correct it!

2023-05-11 06:43 UTC, zuzannapaw commented on packages/ui/TrendChip/index.tsx
> +export const TrendChipStyled = styled.div<TrendChipProps>`
@monika-klokosinska-intive I have applied your suggestions. I added new styles for the case when value is 0, cleaned up the code as @Noshi96 suggested, and added aria-label to the element. The thing is, we can't use dictionnary in /ui folder, therefore text for aria-label is being passed by props. In order to be able to pass to the aria label the proper value  that is being passed as well in prop `value` , I thought about this solution: 

<img width="631" alt="image" src="https://github.com/intive/patronage2023-js/assets/93678778/a8c66067-5fba-4582-a0d1-123e275d5a7e">

It tried it and it seems to work:
   
<img width="241" alt="image" src="https://github.com/intive/patronage2023-js/assets/93678778/496b2b6e-15d2-48fd-88f7-529a14aadb29">

With this change, I update the dictionary as well. What do you think about that?

2023-05-11 06:44 UTC, zuzannapaw commented on packages/ui/TrendChip/index.tsx
> +};
@Noshi96 done! Thank you!

2023-05-11 06:44 UTC, zuzannapaw commented on packages/ui/TrendChip/index.tsx
> +  font-weight: 600;
@Noshi96  done!

2023-05-11 06:45 UTC, zuzannapaw commented on packages/ui/TrendChip/index.tsx
> +    value > 0 ? <span>{value}%</span> : <span>{Math.abs(value)}%</span>;
@Noshi96 I added it and i think it works fine!

2023-05-11 06:57 UTC, zuzannapaw reviewed
@wlechowicz I fixed it and I hope it looks good now! 👀

2023-05-11 09:31 UTC, PawelPazderski approved these changes
Looks and works nice! Only thing I can see is that the "0" option i slighhtly smaller then the others, the icon is flat arrow so I guess it's the padding making the difference, overall great 🚀

2023-05-11 10:26 UTC, monika-klokosinska-intive commented
@wlechowicz this issue seems to be related to storybook not knowing how to load material-icons correctly. I get it sometimes as well, but when I refresh everything is looking good again.

2023-05-11 10:28 UTC, monika-klokosinska-intive approved these changes

2023-05-11 10:28 UTC, merged