refactor: refactor of budgets list based on previous PR #P23-322
intive/patronage2023-js pull request #90
Opened 2023-05-14 09:09 UTC by AzulloCyll

2023-05-14 12:08 UTC, bdeluga requested changes
Small thing to debate on. 👀

2023-05-14 12:08 UTC, bdeluga commented on apps/web/app/(navigation)/SideNavigationBar.tsx
- I feel like there are too many return statements that can be omitted. 
- We could provide some types for next maintainers of our code, and we can also omit using `any`

For example:
```tsx


interface Item {
  id: {
    value: string;
  };
  icon: IconType;
  name: string;
}

interface InifityScrollResponse {
  items: Item[];
}

  const successData =
    data?.pages?.flatMap(({ items }: InifityScrollResponse) =>
      items.map(({ icon, name, id }) => ({
        ComponentToRender: (
          <>
            <IconStyled
              icon={iconNames.includes(icon) ? icon : "help"}
              iconSize={24}
            />
            <SpanStyled>{name}</SpanStyled>
          </>
        ),
        href: `/budgets/${id.value}`,
        id: id.value,
        ref: lastBudgetRef,
      }))
    ) ?? [];

```

Then we could pass contents to `NavList` as `contents={successData}`

2023-05-14 14:33 UTC, AzulloCyll commented on apps/web/app/(navigation)/SideNavigationBar.tsx
done

2023-05-14 21:35 UTC, Noshi96 reviewed
What do you think about declaring these types for the returned data in the fetch and react query functions 🤔?

2023-05-14 21:35 UTC, Noshi96 commented on apps/web/services/mutations.ts
>  }: GetBudgetsListType) => {
```suggestion
}: GetBudgetsListType): Promise<ItemType> => {
```

2023-05-14 21:35 UTC, Noshi96 commented on apps/web/lib/hooks/useGetBudgets.tsx
>      queryFn: async ({ pageParam = 1 }) => {
```suggestion
    queryFn: async ({ pageParam = 1 }): Promise<ItemType> => {
```

2023-05-14 21:35 UTC, Noshi96 commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +      ({ items }: InifityScrollResponse) =>
```suggestion
      ({ items }) =>
```

2023-05-15 09:19 UTC, AzulloCyll commented on apps/web/app/(navigation)/SideNavigationBar.tsx
You are absolutly right :)

2023-05-15 09:54 UTC, AzulloCyll commented
> What do you think about declaring these types for the returned data in the fetch and react query functions 🤔?

I think its goot to have it done. I'll change theese later today.

2023-05-15 09:57 UTC, bdeluga reviewed
LGTM 🚀

2023-05-15 09:57 UTC, bdeluga approved these changes

2023-05-15 14:34 UTC, AzulloCyll commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +      ({ items }: InifityScrollResponse) =>
done

2023-05-15 14:46 UTC, monika-klokosinska-intive approved these changes

2023-05-15 14:49 UTC, merged