feat: administration panel #P23-317
intive/patronage2023-js pull request #92
Opened 2023-05-15 15:20 UTC by bdeluga

### Overview 📖 
[Chore](https://tracker.intive.com/jira/browse/PATRO23-317) was to implement administration panel.

## Features ✨ 
- Now we are able to get signed user role:
```tsx
//SomeFile.tsx

const { data:session } = useSession();

console.log(session?.user.role) // "ADMIN" || "USER"
```
- Users menu is dynamically rendered based on `user's role`

## Fixes 🔨 
- Fixed a lot of console warnings happening due to declaring `styled components` inside of component.
- Fixed logic for rendering active link's state of Navbar.

![ups](https://github.com/intive/patronage2023-js/assets/79754698/9897ab85-fc65-4be3-a76d-a521d7cec728)
- Fixed styles of NavbarLinkItem not taking whole width of parent

2023-05-15 18:41 UTC, wyola reviewed
Great job! Few small suggestions 🤗

PS I don't know within whose task is this, yours or @PawelPazderski but I think this title could be added in this PR, since Paweł's task is strictly about the table, and you create the page here.

![image](https://github.com/intive/patronage2023-js/assets/80450315/9b86ed87-324c-4c69-92b4-8f7411ab08d7)

2023-05-15 18:41 UTC, wyola commented on packages/ui/SideNavigationBar/index.tsx
> +import React, { useState, ReactNode, useMemo } from "react";
we don't need to import `React` and it is not used here

2023-05-15 18:41 UTC, wyola commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +  const NavbarItems = [
it is just a variable, I don't think it needs capital letter in front

```suggestion
  const navbarItems = [
```

2023-05-15 18:41 UTC, wyola commented on apps/web/pages/api/auth/[...nextauth].ts
> +  role: string;
```
  role: 'ADMIN' | 'USER';
```

or 
```
enum UserRole {
  Admin = "ADMIN",
  User = "USER",
}
...

role: UserRole,


// example usage: session?.user.role === UserRole.Admin
```

You could `export` the type and use it as well in `SideNavigationBar.tsx`. This way we don't have hardcoded `magic numbers` 🪄

2023-05-15 18:55 UTC, wlechowicz requested changes

2023-05-15 18:55 UTC, wlechowicz commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +    if (session?.user.role === "ADMIN") {
As a non-admin user, I can easily get access to this by modifying state via dev tools. See if there is a way (there might not be, because we're forced into client components) to have this added server-side so the logic isn't easily accessible client-side.

2023-05-15 18:55 UTC, wlechowicz commented on apps/web/app/(navigation)/users/page.tsx
> +export default function ReportsPage() {
Admin-only pages should be locked behind a middleware check to not allow non-admin users access to the pages, even if they "hack" their way around the menu. Also, component name.

```suggestion
export default function UsersPage() {
```

2023-05-15 18:55 UTC, wlechowicz commented on apps/web/app/(navigation)/users/page.tsx
> +    <MultiCardLayout main={mainCardContent} aside={<DummyAsideCardContent />} />
The aside content for this page is dynamic, initially it's not there, then it shows user details once a user is selected. So this isn't very suitable.

2023-05-15 19:53 UTC, bdeluga commented on apps/web/app/(navigation)/users/page.tsx
> +    <MultiCardLayout main={mainCardContent} aside={<DummyAsideCardContent />} />
It was hard to tell what was in scope of my task, since it had no description at all, so i just created blank page for @PawelPazderski  to work with.

2023-05-15 19:56 UTC, wlechowicz commented on apps/web/app/(navigation)/users/page.tsx
> +    <MultiCardLayout main={mainCardContent} aside={<DummyAsideCardContent />} />
Too bad the description is empty, I agree. But the route and its security is definitely this task - adding the panel. Paweł's task is to fill it with users table (aka content).

2023-05-16 00:10 UTC, bdeluga commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +    if (session?.user.role === "ADMIN") {
I don't think there is a way to do this, as much as I would like to. By what i am testing every component inside of client component is also a client component (?). Omitting "use client" doesn't cause any errors, because component is already client-sided. 
![image](https://github.com/intive/patronage2023-js/assets/79754698/ffb32a11-e826-4186-896c-245fea982874)

![image](https://github.com/intive/patronage2023-js/assets/79754698/3c33d9f2-82f4-4736-83a2-1d1c11bdce7c)

Our layout is "use client" already which makes all of his children "use client" by default. So there is no way of using getServerSession and there is no way of actually rendering navbar based on user's role. 

I hope I am wrong and we can do something about it, I will think about it in the morning.

Moreover, you can easily change role, in react dev tools, but middleware will stop any kinds of breakthrough. 

![image](https://github.com/intive/patronage2023-js/assets/79754698/bffdbe20-c5a9-4f0a-801b-fecaf85fed9f)

2023-05-16 09:11 UTC, bdeluga commented on apps/web/app/(navigation)/SideNavigationBar.tsx
> +    if (session?.user.role === "ADMIN") {
Added middleware, it safely guards all sensitive routes.

2023-05-16 11:14 UTC, mpiwonski approved these changes
Good job @bdeluga!

2023-05-16 11:26 UTC, wlechowicz approved these changes
Obligatory 🚀 and LGTM

2023-05-16 11:54 UTC, wyola approved these changes
:shipit:

2023-05-16 12:15 UTC, monika-klokosinska-intive approved these changes

2023-05-16 13:56 UTC, merged