fix: transactions table skeleton refinement #P23-320
intive/patronage2023-js pull request #94
Opened 2023-05-15 18:50 UTC by zuzannapaw

<h1>Transactions table skeleton refinement 🚧  </h1>

<h2>What changed ✏️ </h2>

- `isLoading` from `react query` has been passed to `<TransactionsTable/>`
- When the data is loading, all `th` are visible, they are not suspended. Skeleton is applied only inside `table body`
- Because we are not sure how many transactions will come to user, `gradient` has been applied as well
- By preserving the structure of html table, content is being properly displayed

<h2>Adjustement 🚀 </h2>

- By extending `ITableBodyProps` : 

```typescript
interface TransactionsTableSuspenseProps extends ITableBodyProps {
  rowsNumber: number;
}
``` 
it is possible now to pass prop `rowsNumber`  to `<TransactionsTableSuspense/>` . It defines how many `<DataRows/>` we would like to display.  Prop `rowsNumber` is used in function `spawnRows()` : 

```javascript
//function for creating array full of <DataRow/> components
const spawnRows = (props: TransactionsTableSuspenseProps) => {
  const rowsArray = [];
  let id = 1;

  for (let i = 0; i < **props.rowsNumber**; i++) {
    rowsArray.push(<DataRow {...props} key={id++} />);
  }

  return rowsArray;
};
``` 
Thanks to that, we are not limited in rows number.  If we would like to, we could pass here as well `itemsPerPage` to display the accurate number of rows that has been chosen by user in `Pagination`. 

- With classes from `/css/transactionsTableSuspense.css` ,the table is responsive 💻

2023-05-15 19:16 UTC, wlechowicz requested changes
LGTM, one improvement requested.

2023-05-15 19:16 UTC, wlechowicz commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +          transactionsData ? transactionsData : ([] as Transaction[])
It would be better if TransactionTable handled this, if the vale is not passed it should default to []. Also this could be simplified to `transactions={ transactionsData || [] }` but it's better to handle this via parameter default value in the component.

2023-05-15 20:16 UTC, mpiwonski approved these changes
Good job @zuzannapaw!

2023-05-15 20:31 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +          transactionsData ? transactionsData : ([] as Transaction[])
@wlechowicz  Thanks for your comment, I will fix it tomorrow!

2023-05-15 21:33 UTC, Noshi96 commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTableSuspense.tsx
> +import "../../../css/transactionsTableSuspense.css";
This makes me wonder if it's OK that the CSS directory is inside the /app. 🤔 If it were in the /web, we would simply write import `"css/transactionsTableSuspense.css";`

2023-05-16 07:41 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTableSuspense.tsx
> +    <tr>
@Noshi96 when I didn't add that, typescript was screaming :/

2023-05-16 07:43 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTableSuspense.tsx
> +    <tr>
@Noshi96  thank you, i am going to apply your suggestion ☺️

2023-05-16 08:35 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTableSuspense.tsx
> +import "../../../css/transactionsTableSuspense.css";
@Noshi96  I tried that and I'm getting an error that this file is not found :/

2023-05-16 08:44 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +          transactionsData ? transactionsData : ([] as Transaction[])
@wlechowicz  it's fixed :)

2023-05-16 08:44 UTC, zuzannapaw commented on apps/web/app/(navigation)/budgets/[id]/TransactionsTableSuspense.tsx
> +    <tr>
@Noshi96  done! :)

2023-05-16 10:26 UTC, Noshi96 approved these changes
LGTM 🎸

2023-05-16 11:09 UTC, wlechowicz approved these changes

2023-05-16 11:24 UTC, merged