feat: budget details - filtering by categories #P23-224
intive/patronage2023-js pull request #97
Opened 2023-05-17 18:02 UTC by Noshi96

2023-05-18 08:03 UTC, mpiwonski approved these changes
Good job @Noshi96!

2023-05-18 09:13 UTC, Noshi96 commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +  useEffect(() => {
This component renders every time the categoryFilterState changes, so it will work without the useEffect. This particular useEffect is responsible for resetting the pagination page when the categoryFilterState changes.

2023-05-18 10:21 UTC, aniasgit requested changes
If you select a category and switch to a different budget, the new budget shows you data filtered by this category, although it is not marked that the category has been selected.

2023-05-18 10:28 UTC, aniasgit commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +            transactionType: null,
I think transactionType can be removed from here. It's in my task, in a different version, adding it to yours will only cause unnecessary conflicts. According to swagger, not passing transactionType in the query will set it to null anyway on the BE side

2023-05-18 18:19 UTC, wlechowicz approved these changes
LGTM, one refactor request

2023-05-18 18:19 UTC, wlechowicz commented on apps/web/components/CategoryFilterForm/index.tsx
> +`;
Put all this stuff in a separate file, please.

2023-05-18 19:17 UTC, Noshi96 commented on apps/web/app/(navigation)/budgets/[id]/TransactionTableController.tsx
> +            transactionType: null,
Done :D

2023-05-18 19:18 UTC, Noshi96 commented on apps/web/components/CategoryFilterForm/index.tsx
> +`;
Done :D

2023-05-18 19:22 UTC, monika-klokosinska-intive commented on apps/web/components/CategoryFilterForm/index.tsx
> +        queryClient.invalidateQueries(["datatable"]);
@Noshi96 is it necessary to invalidate the query here? Won't the query re-run anyway because "categoryFilterState" changed?

2023-05-18 19:36 UTC, aniasgit approved these changes
Now it works good, great job 👍

2023-05-18 20:06 UTC, PawelPazderski reviewed
What does the `manage` stand for? It's taking me back to:
![image](https://github.com/intive/patronage2023-js/assets/72406958/a562ba03-5411-49c8-95e7-1632af213d03)
Why is it here if the input selecting shows the filtering straight away?

2023-05-18 20:14 UTC, Alessiass approved these changes
Looks nice, works nice and utilizes Jotai. Kudos! 👻

2023-05-18 21:43 UTC, Vectari approved these changes
Sorry for complaining but I'm not sure about this yellow on yellow in "Refund". 
It stands out slightly from the others. Anyway works great!
![002](https://github.com/intive/patronage2023-js/assets/93955642/5629fc0f-c7bb-41f9-a23c-852fbe047c23)

2023-05-21 21:06 UTC, zuzannapaw reviewed
The smaller card has become alive and finally dummy aside card content doesn't need to be imported! 🚀 

 A question from me: now, new category "Salary" has the same icon as one of the possible icons from icon picker for whole budget:   

![image](https://github.com/intive/patronage2023-js/assets/93678778/1fbea29b-c8c2-477c-858d-08dbcb7ad5ba)


![image](https://github.com/intive/patronage2023-js/assets/93678778/b4a86bcb-0041-4f8f-b602-4b234443e315)

I'm not sure it won't be confusing. What do you think about that?

2023-05-21 21:28 UTC, Noshi96 commented on apps/web/components/CategoryFilterForm/index.tsx
> +        queryClient.invalidateQueries(["datatable"]);
I agree with you that `queryClient.invalidateQueries` isn't needed in this situation. Already fixed. Thanks! :D

2023-05-21 21:30 UTC, Noshi96 commented
> May I ask - What does the `manage` stand for? It's taking me back to: Why is it here if the selecting inputs shows the filtering straight away? Which looks and works nice by the way

@PawelPazderski 'manage' comes from the design. It looks like an unused element, some space filler. You are right that redirecting the user to the "/" page isn't the best solution. I changed it to a simple button with an empty call () =>{}. Thanks! :)

2023-05-21 21:31 UTC, Noshi96 commented
> 



> Sorry for complaining but I'm not sure about this yellow on yellow in "Refund". It stands out slightly from the others. Anyway works great! ![002](https://user-images.githubusercontent.com/93955642/239386987-5629fc0f-c7bb-41f9-a23c-852fbe047c23.PNG)

Good point @Vectari! I have changed the contrast of the icon and its background

2023-05-21 21:53 UTC, Noshi96 commented
> The smaller card has become alive and finally dummy aside card content doesn't need to be imported! 🚀
> 
> A question from me: now, new category "Salary" has the same icon as one of the possible icons from icon picker for whole budget:
> 
> ![image](https://user-images.githubusercontent.com/93678778/239768131-1fbea29b-c8c2-477c-858d-08dbcb7ad5ba.png)
> 
> ![image](https://user-images.githubusercontent.com/93678778/239767992-b4a86bcb-0041-4f8f-b602-4b234443e315.png)
> 
> I'm not sure if it won't be confusing. What do you think about that?

@zuzannapaw thanks for your comment! TBH, I feel that the icons available in the icon picker aren't that important. I believe that the icon, along with its name, displayed in the aside card, is sufficient for users to understand its representation and function. If you have any suggestions for alternative icons that could be used, I am open to considering them.

2023-05-22 07:35 UTC, bdeluga commented on apps/web/components/CategoryFilter/index.tsx
> +    {} as CategoryFilterType
`Array.reduce` are allways complex another good solution would be 
```tsx
Object.fromEntries(Object.keys(categoryMap).map((key)=>[key,false])) as CategoryFilterType
```

2023-05-22 10:07 UTC, bdeluga approved these changes
LGTM 🚀 
One comment to maybe have chat about, not to change in particular.

2023-05-22 11:23 UTC, monika-klokosinska-intive commented on apps/web/components/CategoryFilter/index.tsx
> +    {} as CategoryFilterType
@bdeluga @Noshi96 another idea: just use array to store the selected categories. `[]` is the starting state (meaning no category was selected), once the user selected something, it is added to the array (e.g.  `['Subscriptions']` or whichever field is best used as key). 
If something is not in the array, it means it's not selected. There is a lot of code that transforms the object into an array and then back to object again. It will be simpler to just stick to an array all the time.

2023-05-22 15:36 UTC, Noshi96 commented on apps/web/lib/dictionary.tsx
> +      pl: "Pensja",
done :D

2023-05-22 15:47 UTC, Noshi96 commented on apps/web/components/CategoryFilter/index.tsx
> +    {} as CategoryFilterType
Thanks, @bdeluga for showing an alternative to Array.reduce. @monika-klokosinska-intive I think your suggestion of using an array to store selected categories is very good indeed. I had complicated my solution. I have now applied your suggestions and I think it works better, thanks!

2023-05-22 16:01 UTC, wyola approved these changes

2023-05-22 16:25 UTC, AzulloCyll approved these changes

2023-05-22 16:41 UTC, merged