feat: budget edit backend integration #P23-292
intive/patronage2023-js pull request #98
Opened 2023-05-17 19:11 UTC by PawelPazderski

## Adding BE integration to budget edit modal
Ticket: https://tracker.intive.com/jira/browse/PATRO23-292

Providing slight changes to IconPicker, which was causing the submit.
At the moment modal closes & the budget changes on success, if BE status is not successful - ErrorMessage is displayed in the modal.

2023-05-17 22:24 UTC, bdeluga approved these changes
1. Edited budget.
2. It worked very well.
3. Made me happy.
4. Profit ? LGTM 🚀 

Small thing to change, but it wont _change_ my feedback (hehe get it?) :smile:

2023-05-17 22:24 UTC, bdeluga commented on packages/ui/IconPicker/index.tsx
If our function expects same event input as react's `onClick` we could pass function as  a reference instead of calling it with arrow syntax,

Those onClicks didn't need refactor.

2023-05-18 08:11 UTC, mpiwonski approved these changes
Good job @PawelPazderski :)

2023-05-18 08:11 UTC, mpiwonski commented on apps/web/app/(navigation)/EditBudget.tsx
> +  const sendEditedBudgetMutation = useMutation({
Could you please tell me why we use 'useMutation' hook here? Thanks :)

2023-05-18 08:18 UTC, PawelPazderski commented on packages/ui/IconPicker/index.tsx
You are right, I'll change that, thanks!

2023-05-18 08:27 UTC, PawelPazderski commented on apps/web/app/(navigation)/EditBudget.tsx
> +  const sendEditedBudgetMutation = useMutation({
Let me quote the documentation: 
*Unlike queries, mutations are typically used to create/update/delete data or perform server side-effects. For this purpose, TanStack Query exports a useMutation hook.* 
📖 https://tanstack.com/query/v4/docs/react/guides/mutations

2023-05-18 12:01 UTC, aniasgit approved these changes
Looks good to me 👍

2023-05-18 15:05 UTC, zuzannapaw approved these changes
Looks and works great, congrats! 🚀 😃

2023-05-18 17:42 UTC, Alessiass approved these changes
Looks good and works good 👍

2023-05-18 18:04 UTC, PawelPazderski commented on apps/web/app/(navigation)/EditBudget.tsx
>      useValidateBudgetModal("AddNewBudgetModal");
Yep, that's a good thought

2023-05-18 19:47 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/EditBudget.tsx
> +  const sendEditedBudgetMutation = useMutation({
@mpiwonski tl;dr 
fetching data = query
modifying data in any form = mutation
That's the golden rule across many approaches (same convention is used in graphql for example).

2023-05-18 20:14 UTC, monika-klokosinska-intive commented
@PawelPazderski  
<img width="1440" alt="Screenshot 2023-05-18 at 22 09 19" src="https://github.com/intive/patronage2023-js/assets/46372708/464f171a-ada6-45c3-acfe-845431a541d9">
The position of the error messaging definitely leaves room for improvement. I am not sure if this is part of your task or if you are waiting for Mateusz to move the error messaging out of the modal BUT we definitely need to improve the visuals here - if not in this PR, then in a follow up once Matuesz's changes are merged.  Please keep your eyes peeled on this!

2023-05-18 20:19 UTC, monika-klokosinska-intive requested changes

2023-05-18 20:19 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/EditBudget.tsx
> +            setErrMsg("Wrong data");
@PawelPazderski the error messaging here should come from dictionary - otherwise there is no way to support other languages than English.

2023-05-18 20:22 UTC, monika-klokosinska-intive commented
@PawelPazderski please note that the "Vercel Preview Comments" job is failing... looks like some busybodies left you comments inside the vercel preview. If you click on "Details" next to job, you can see what's going on with that.

2023-05-18 21:22 UTC, Vectari approved these changes
Works great!

2023-05-22 00:38 UTC, Noshi96 approved these changes
Great job! 🚀 It works and looks very good. There are two small changes I would suggest:

2023-05-22 00:38 UTC, Noshi96 commented on apps/web/app/(navigation)/CreateNewBudget.styled.tsx
> +  top: 125px;
I think we can use a smaller z-index 😄

2023-05-22 00:38 UTC, Noshi96 commented on apps/web/app/(navigation)/EditBudget.tsx
> +  name: string,
Please change the letter to a capital letter
```suggestion

interface EditedBudgetBEProps {
  name: string,
```

2023-05-22 05:58 UTC, AzulloCyll approved these changes
LGTM!

2023-05-22 09:47 UTC, PawelPazderski commented on apps/web/app/(navigation)/EditBudget.tsx
> +  name: string,
Changed, thanks

2023-05-22 14:19 UTC, Noshi96 approved these changes

2023-05-22 18:36 UTC, monika-klokosinska-intive commented on apps/web/app/(navigation)/CreateNewBudget.styled.tsx
> +  top: 125px;
@PawelPazderski yeah, please chill with the value here, how about a `5` or something?

2023-05-22 18:37 UTC, monika-klokosinska-intive approved these changes

2023-05-22 19:02 UTC, PawelPazderski commented on apps/web/app/(navigation)/CreateNewBudget.styled.tsx
> +  top: 125px;
Sure 😄

2023-05-22 19:07 UTC, merged